/**
 * SparkLabs 포트폴리오 시드 데이터.
 * 전체 550+ 중 브랜드·AI 스포트라이트 중심의 대표 셀렉션.
 * 향후 관리자 콘솔/스프레드시트 연동 전까지의 source of truth.
 */

export type PortfolioCategory =
  | 'ai'
  | 'fintech'
  | 'bio'
  | 'mobility'
  | 'saas'
  | 'commerce'
  | 'hrtech'
  | 'agrifood'
  | 'security'
  | 'media'
  | 'consumer'
  | 'proptech'
  | 'deeptech'
  | 'other';

export type PortfolioStage =
  | 'Seed'
  | 'Pre-A'
  | 'Series A'
  | 'Series B'
  | 'Series C+'
  | 'Public'
  | 'Exited';

export interface PortfolioCompany {
  slug: string;
  name: string;
  tagline: { ko: string; en: string };
  category: PortfolioCategory;
  entity: string; // entity slug
  country: string; // ISO-ish short code e.g. 'KR', 'US', 'AU'
  stage?: PortfolioStage;
  year?: string;
  website?: string;
  /** True if this company should surface in the AI Portfolio Spotlight page. */
  aiPick?: boolean;
  /** True if this is a marquee brand-defining name for SparkLabs. */
  featured?: boolean;
  /** Optional note rendered in cards (exit, milestone). */
  highlight?: { ko: string; en: string };
  /** Logo filename under /public/portfolio/logos/ */
  logoFile?: string;
}

const globalAiLeaders: PortfolioCompany[] = [
  {
    slug: 'openai',
    name: 'OpenAI',
    tagline: {
      ko: 'ChatGPT를 만든 AI 연구·배포 리더',
      en: 'The research and deployment leader behind ChatGPT',
    },
    category: 'ai',
    entity: 'group',
    country: 'US',
    logoFile: 'openai.svg',
    stage: 'Series C+',
    aiPick: true,
    featured: true,
    highlight: {
      ko: '2024년 1월 펀딩 라운드 9개 초청 투자사 중 하나로 참여',
      en: 'Invited as one of nine investors in the January 2024 funding round',
    },
  },
  {
    slug: 'anthropic',
    name: 'Anthropic',
    tagline: {
      ko: '안전하고 조향 가능한 AI를 추구하는 AI 연구소',
      en: 'An AI safety company building steerable, reliable AI systems',
    },
    category: 'ai',
    entity: 'group',
    country: 'US',
    logoFile: 'anthropic.svg',
    stage: 'Series C+',
    aiPick: true,
    featured: true,
  },
  {
    slug: 'perplexity',
    name: 'Perplexity',
    tagline: {
      ko: 'AI-native 검색 엔진',
      en: 'AI-native answer engine for the web',
    },
    category: 'ai',
    entity: 'group',
    country: 'US',
    logoFile: 'perplexity.svg',
    stage: 'Series C+',
    aiPick: true,
    featured: true,
  },
  {
    slug: 'xai',
    name: 'xAI (Grok)',
    tagline: {
      ko: 'Elon Musk가 설립한 AI 연구소',
      en: "Elon Musk's AI research company",
    },
    category: 'ai',
    entity: 'group',
    country: 'US',
    logoFile: 'xai.svg',
    stage: 'Series C+',
    aiPick: true,
    featured: true,
    highlight: {
      ko: '2026년 SpaceX에 인수',
      en: 'Acquired by SpaceX in 2026',
    },
  },
  {
    slug: 'groq',
    name: 'Groq',
    tagline: {
      ko: '세계에서 가장 빠른 AI 추론 하드웨어',
      en: 'The fastest AI inference silicon in the world',
    },
    category: 'ai',
    entity: 'group',
    country: 'US',
    logoFile: 'groq.svg',
    stage: 'Exited',
    aiPick: true,
    featured: true,
    highlight: {
      ko: '2025년 NVIDIA에 $20B 규모 자산·라이선싱 딜로 편입',
      en: 'Joined NVIDIA in 2025 via a $20B asset & licensing deal',
    },
  },
];

const koreaCore: PortfolioCompany[] = [
  {
    slug: 'quadmedicine',
    name: 'QuadMedicine',
    tagline: {
      ko: '세계 최초 GMP-compliant medical microneedle',
      en: "World's first GMP-compliant medical microneedle platform",
    },
    category: 'bio',
    entity: 'biolabs',
    country: 'KR',
    logoFile: 'quadmedicine.png',
    stage: 'Public',
    featured: true,
    highlight: {
      ko: 'KOSDAQ 상장 · Bill & Melinda Gates Foundation 그랜트',
      en: 'Listed on KOSDAQ · Grant from Bill & Melinda Gates Foundation',
    },
  },
  {
    slug: 'sparkplus',
    name: 'SparkPlus',
    tagline: {
      ko: '한국 대표 프리미엄 오피스 플랫폼',
      en: "Korea's premium workspace network",
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'sparkplus.png',
    stage: 'Series C+',
    featured: true,
  },
  {
    slug: 'wanted',
    name: 'Wanted',
    tagline: {
      ko: '데이터 기반 채용 플랫폼',
      en: 'Data-driven recruiting platform',
    },
    category: 'hrtech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'wanted.png',
    stage: 'Public',
    featured: true,
  },
  {
    slug: 'alganize',
    name: 'Alganize',
    tagline: {
      ko: '문서 중심 AI 리서치 어시스턴트',
      en: 'AI research assistant for documents',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'alganize.png',
    stage: 'Series A',
    aiPick: true,
  },
  {
    slug: 'fescaro',
    name: 'FESCARO',
    tagline: {
      ko: '차세대 차량 사이버 보안 솔루션',
      en: 'Next-generation automotive cybersecurity',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'fescaro.png',
    stage: 'Series B',
  },
  {
    slug: 'muzlive',
    name: 'Muzlive',
    tagline: {
      ko: 'K-pop 팬 IP 플랫폼 (Kit앨범)',
      en: 'K-pop fan IP platform behind the Kit album',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'muzlive.png',
    stage: 'Series B',
  },
  {
    slug: 'kokozi',
    name: 'kokozi',
    tagline: {
      ko: '세계 진출한 키즈 콘텐츠·IP',
      en: 'Kids IP & content studio with global reach',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kokozi.png',
    stage: 'Series B',
  },
  {
    slug: 'genoplan',
    name: 'Genoplan',
    tagline: {
      ko: '컨슈머 유전자·헬스케어',
      en: 'Consumer genomics & healthcare',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'genoplan.png',
    stage: 'Series B',
  },
  {
    slug: 'blocko',
    name: 'Blocko',
    tagline: {
      ko: '엔터프라이즈 블록체인 인프라',
      en: 'Enterprise blockchain infrastructure',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'blocko.png',
    stage: 'Series B',
  },
  {
    slug: 'obzen',
    name: 'Obzen',
    tagline: {
      ko: 'AI 기반 금융 범죄·AML 솔루션',
      en: 'AI-driven financial crime & AML platform',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'obzen.png',
    stage: 'Series B',
    aiPick: true,
  },
  {
    slug: 'reco',
    name: 'Reco',
    tagline: {
      ko: 'SaaS 보안 거버넌스',
      en: 'SaaS security governance platform',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'reco.png',
    stage: 'Series A',
  },
  {
    slug: 'switchon',
    name: 'Switchon',
    tagline: {
      ko: '전력 IoT · 산업 AI',
      en: 'Power IoT & industrial AI',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'switchon.png',
    stage: 'Series A',
    aiPick: true,
  },
  {
    slug: 'ssenstone',
    name: 'SSenStone',
    tagline: {
      ko: '동적 본인인증 보안 플랫폼',
      en: 'Dynamic authentication security platform',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'ssenstone.png',
    stage: 'Series B',
  },
  {
    slug: 'gint',
    name: 'GINT',
    tagline: {
      ko: '스포츠 데이터·커뮤니티',
      en: 'Sports data & community platform',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'gint.png',
    stage: 'Series A',
  },
  {
    slug: 'bemyfriends',
    name: 'bemyfriends',
    tagline: {
      ko: '글로벌 팬 커머스 플랫폼',
      en: 'Global fandom commerce platform',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bemyfriends.png',
    stage: 'Series B',
  },
  {
    slug: 'mbx',
    name: 'MBX',
    tagline: {
      ko: 'Web3 게임·컨슈머 앱 플랫폼',
      en: 'Web3 gaming & consumer app platform',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'mbx.png',
    stage: 'Series B',
  },
  {
    slug: 'nthing',
    name: 'N.THING',
    tagline: {
      ko: '모듈형 수직농장',
      en: 'Modular vertical farming company',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'nthing.png',
    stage: 'Series B',
  },
  {
    slug: 'sentbe',
    name: 'SentBe',
    tagline: {
      ko: '글로벌 B2B 국가간 송금',
      en: 'Global B2B cross-border payments',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'sentbe.png',
    stage: 'Series C+',
  },
  {
    slug: 'peaches',
    name: 'Peaches',
    tagline: {
      ko: '모빌리티·소비자 앱',
      en: 'Consumer mobility app',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'peaches.png',
    stage: 'Series A',
  },
  {
    slug: 'caredoc',
    name: '케어닥',
    tagline: {
      ko: '시니어 케어 플랫폼',
      en: 'Senior-care matching & service platform',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'caredoc.png',
    stage: 'Series B',
  },
  {
    slug: 'aboraLabs',
    name: 'Abora Labs',
    tagline: {
      ko: 'AI 기반 언어 학습 플랫폼',
      en: 'AI-powered language learning platform',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'aboraLabs.png',
    stage: 'Seed',
    aiPick: true,
  },
];


const scrapedCompanies: PortfolioCompany[] = [
  {
    slug: 'bitsensing',
    name: '비트센싱',
    tagline: {
      ko: 'AIR 4D (자율주행 환경을 위한 이미징 레이더 솔루션)',
      en: 'AIR 4D (imaging radar solution for autonomous driving environments)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bitsensing.jpg',
  },
  {
    slug: 'equal-table-inc',
    name: '주식회사 이퀄테이블',
    tagline: {
      ko: 'Foodtech',
      en: 'foodtech',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'equal-table-inc.png',
  },
  {
    slug: 'danstruct-co-ltd',
    name: '주식회사 댄스트럭트',
    tagline: {
      ko: 'Media',
      en: 'Media',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'danstruct-co-ltd.png',
  },
  {
    slug: 'spring-again-co-ltd',
    name: '주식회사 스프링어게인',
    tagline: {
      ko: 'Medicaltech',
      en: 'Medicaltech',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'spring-again-co-ltd.png',
  },
  {
    slug: 'bueno-company-co-ltd',
    name: '(주)부에노컴퍼니',
    tagline: {
      ko: 'Distribution',
      en: 'Distribution',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bueno-company-co-ltd.png',
  },
  {
    slug: 'polymerize-korea-llc',
    name: '폴리머라이즈코리아유한회사',
    tagline: {
      ko: '폴리머라이즈는 AI 기반 산업 연구개발 플랫폼으로, 기업의 실험 데이터를 하나로 통합하고 AI를 활용해 더 빠르고 정확한 실험 설계를 지원합니다.',
      en: 'Polymerize is an AI-based industrial research and development platform that integrates a company\'s experimental data into one and utilizes AI to support faster and more accurate experimental design.',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'polymerize-korea-llc.png',
  },
  {
    slug: 'skylabs',
    name: '스카이랩스',
    tagline: {
      ko: 'Healthcare',
      en: 'Healthcare',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'skylabs.png',
  },
  {
    slug: 'queen-live-queen-of-shopping',
    name: '퀸라이브 (쇼핑의 여왕)',
    tagline: {
      ko: '여성 패션을 책임지는 라이브쇼핑 플랫폼, 쇼핑의여왕!',
      en: 'A live shopping platform responsible for women’s fashion, Queen of Shopping!',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'queen-live-queen-of-shopping.jpg',
  },
  {
    slug: 'wave-corp',
    name: '웨이브코퍼레이션',
    tagline: {
      ko: '그룹 영상통화를 통해 게임·콘텐츠를 함께 즐기는 플랫폼 \'웨이브(WAVE)\' 운영사',
      en: 'Operator of ‘WAVE’, a platform to enjoy games and content together through group video calls',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'wave-corp.jpg',
  },
  {
    slug: 'doubleme',
    name: '더블미',
    tagline: {
      ko: 'VR',
      en: 'VR',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'doubleme.jpg',
  },
  {
    slug: 'h2o-hospitality',
    name: 'H2O호스피탈리티',
    tagline: {
      ko: '숙박, 레저 산업의 DX 를 선도하는 아시아 1위 호스피탈리티 테크 기업',
      en: 'Asia\'s No. 1 hospitality tech company leading DX in the lodging and leisure industry',
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'h2o-hospitality.jpg',
  },
  {
    slug: 'impactus',
    name: '임팩터스',
    tagline: {
      ko: '학생 개인 맞춤형 수업 개설-운영-피드백-평가 올인원 솔루션, 임팩트 스페이스를 운영하고 있습니다.',
      en: 'We operate Impact Space, an all-in-one solution for creating personalized classes for students - operation - feedback - evaluation.',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'impactus.png',
  },
  {
    slug: 'pierrot-company-inc',
    name: '(주)피에로컴퍼니',
    tagline: {
      ko: 'ESG',
      en: 'ESG',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'pierrot-company-inc.png',
  },
  {
    slug: 'kangsters-corp',
    name: '캥스터즈 주식회사',
    tagline: {
      ko: 'Able-Tech',
      en: 'Able-Tech',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kangsters-corp.png',
  },
  {
    slug: 'zest-inc',
    name: '제스트 주식회사',
    tagline: {
      ko: 'ESG',
      en: 'ESG',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'zest-inc.png',
  },
  {
    slug: 'havehad',
    name: '해브해드',
    tagline: {
      ko: '시티보이 패션의 옷을 판매하며 다양한 이벤트를 동시에 진행하는 기업',
      en: 'A company that sells City Boy Fashion clothes and holds various events at the same time.',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'havehad.png',
  },
  {
    slug: 'allganize',
    name: '올거나이즈',
    tagline: {
      ko: '엔터프라이즈 AI 솔루션 기업',
      en: 'Enterprise AI solution company',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'allganize.png',
  },
  {
    slug: 'gapt',
    name: '갭텍',
    tagline: {
      ko: 'ESG',
      en: 'ESG',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'gapt.png',
  },
  {
    slug: 'shutagen',
    name: '슈타겐',
    tagline: {
      ko: 'Manufacturing',
      en: 'Manufacturing',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'shutagen.png',
  },
  {
    slug: 'gelko',
    name: '젤코',
    tagline: {
      ko: 'Hardware',
      en: 'Hardware',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'gelko.png',
  },
  {
    slug: 'slowave',
    name: '슬로웨이브',
    tagline: {
      ko: 'Healthcare',
      en: 'Healthcare',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'slowave.png',
  },
  {
    slug: 'lehosah',
    name: '르호사',
    tagline: {
      ko: 'Fashion',
      en: 'Fashion',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'lehosah.png',
  },
  {
    slug: 'beamstudio',
    name: '빔스튜디오',
    tagline: {
      ko: 'Entertainment',
      en: 'Entertainment',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'beamstudio.png',
  },
  {
    slug: 'logispot',
    name: '로지스팟',
    tagline: {
      ko: 'Platform',
      en: 'Platform',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'logispot.jpg',
  },
  {
    slug: 'qubit-security',
    name: '큐비트시큐리티',
    tagline: {
      ko: '클라우드, 온프레미스를 아우르는 정보 보안 솔루션 및 서비스 전문 기업',
      en: 'A company specializing in information security solutions and services encompassing cloud and on-premise',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'qubit-security.jpg',
  },
  {
    slug: 'paywork',
    name: '페이워크',
    tagline: {
      ko: '프리랜서, 특수고용근로자 등을 위한 업무 정산 관리 서비스',
      en: 'Work settlement management service for freelancers, specially employed workers, etc.',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'paywork.jpg',
  },
  {
    slug: 'liche',
    name: '리체',
    tagline: {
      ko: 'K-BNPL(장기분할납부) 결제 솔루션의 대중화를 선도하는 핀테크 스타트업',
      en: 'A fintech startup leading the popularization of K-BNPL (long-term installment payment) payment solutions.',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'liche.jpg',
  },
  {
    slug: 'kupa',
    name: '쿠파',
    tagline: {
      ko: 'AI로 금융 데이터를 분석해 인사이트를 제공하는 스타트업',
      en: '',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kupa.jpg',
  },
  {
    slug: 'draftype',
    name: '드래프타입',
    tagline: {
      ko: '커스텀모델 제작 기반 콘텐츠 제작, 드래프타입 스튜디오',
      en: 'Content production based on custom model production, DraftType Studio',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'draftype.jpg',
  },
  {
    slug: 'databean',
    name: '데이터빈',
    tagline: {
      ko: '차세대 데이터센터용 이머전 쿨링 솔루션',
      en: 'Immersion cooling solution for next-generation data centers',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'databean.jpg',
  },
  {
    slug: 'stylemate',
    name: '스타일메이트',
    tagline: {
      ko: 'Fashion',
      en: 'Fashion',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'stylemate.jpg',
  },
  {
    slug: 'pulsead',
    name: '펄스애드',
    tagline: {
      ko: '리테일 셀러를 위한 이커머스 통합 광고 플랫폼',
      en: 'E-commerce integrated advertising platform for retail sellers',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'pulsead.jpg',
  },
  {
    slug: 'itgreen',
    name: '잇그린',
    tagline: {
      ko: '친환경 다회용기 서비스',
      en: 'Eco-friendly reusable container service',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'itgreen.jpg',
  },
  {
    slug: 'whatap-labs',
    name: '와탭랩스',
    tagline: {
      ko: '국내 1위 SaaS형 모니터링 서비스',
      en: 'Korea’s No. 1 SaaS-type monitoring service',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'whatap-labs.jpg',
  },
  {
    slug: 'uuuuu',
    name: '유유유유유',
    tagline: {
      ko: '글로벌 디자이너들과의 콜라보레이션을 통한 감각적인 디자인의 셀프젤네일 서비스',
      en: 'Self-gel nail service with sensuous design through collaboration with global designers',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'uuuuu.jpg',
  },
  {
    slug: 'edgecross-1',
    name: '엣지크로스',
    tagline: {
      ko: 'Software Development',
      en: 'Software Development',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'edgecross-1.jpg',
  },
  {
    slug: 'carmerce',
    name: '카머스',
    tagline: {
      ko: 'Mobility',
      en: 'Mobility',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'carmerce.jpg',
  },
  {
    slug: 'sparkpet-knollo',
    name: '스파크펫 (놀로)',
    tagline: {
      ko: '반려동물 온오프라인 통합 플랫폼',
      en: 'Pet online/offline integrated platform',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'sparkpet-knollo.jpg',
  },
  {
    slug: 'toothnote',
    name: '지아이빌리언스 (투스노트)',
    tagline: {
      ko: 'Life Style',
      en: 'Lifestyle',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'toothnote.jpg',
  },
  {
    slug: 'eatmapl',
    name: '잇마플 (맛있저염)',
    tagline: {
      ko: 'Medifood',
      en: 'Medifood',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'eatmapl.jpg',
  },
  {
    slug: 'vanilabrain-sellerking',
    name: '바닐라브레인 (장사왕)',
    tagline: {
      ko: 'SaaS',
      en: 'SaaS',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'vanilabrain-sellerking.jpg',
  },
  {
    slug: 'astar-copykle',
    name: '아스타 (카피클)',
    tagline: {
      ko: 'Copywriting',
      en: 'Copywriting',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'astar-copykle.jpg',
  },
  {
    slug: 'mineis-charan',
    name: '마인이스 (차란)',
    tagline: {
      ko: '품질보증된 상품을 구매할수있는 온라인 세컨핸드 백화점',
      en: 'Online second hand department store where you can purchase quality guaranteed products',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'mineis-charan.jpg',
  },
  {
    slug: 'dosigotgan',
    name: '도시곳간',
    tagline: {
      ko: 'F&B',
      en: 'F&B',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'dosigotgan.jpg',
  },
  {
    slug: 'medithings',
    name: '메디띵스',
    tagline: {
      ko: '인공지능기반 개인맞춤형 웨어러블 디지털 헬스케어 시스템',
      en: 'Artificial intelligence-based personalized wearable digital healthcare system',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'medithings.jpg',
  },
  {
    slug: 'baegen',
    name: '배젠',
    tagline: {
      ko: 'Pharmaceuticals',
      en: 'Pharmaceuticals',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'baegen.jpg',
  },
  {
    slug: 'damhwa-company',
    name: '담화컴퍼니 (술담화)',
    tagline: {
      ko: 'F&B',
      en: 'F&B',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'damhwa-company.jpg',
  },
  {
    slug: 'midbar',
    name: '미드바르',
    tagline: {
      ko: '물 요구량을 99% 절감한 공기주입식 에어로포닉스 스마트팜',
      en: 'Inflatable aeroponics smart farm that reduces water requirements by 99%',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'midbar.jpg',
  },
  {
    slug: 'langcode-inc',
    name: '주식회사 랭코드',
    tagline: {
      ko: '글로벌 대기업이 선택한 기업용 생성형 AI 플랫폼',
      en: 'Generative AI platform for enterprises selected by global conglomerates',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'langcode-inc.jpg',
  },
  {
    slug: 'livit-tansolution',
    name: '리빗 (탄솔루션)',
    tagline: {
      ko: '기업용 탄소배출관리 솔루션',
      en: 'Carbon emissions management solution for businesses',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'livit-tansolution.jpg',
  },
  {
    slug: 'accurie-biosciences',
    name: '에큐리바이오',
    tagline: {
      ko: '엔지니어링 파아지 플랫폼으로 치료제와 새로운 약물전달법을 개발한 바이오기업',
      en: 'A bio company that developed treatments and new drug delivery methods using an engineered phage platform.',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'accurie-biosciences.jpg',
  },
  {
    slug: 'inogenix-inc-oncocheck',
    name: '이노제닉스 (온코체크)',
    tagline: {
      ko: '대장암을 예방하기 위해 더 편리하고 정확한 혈액검사를 개발하는 분자진단 기업',
      en: 'A molecular diagnostics company that develops more convenient and accurate blood tests to prevent colon cancer.',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'inogenix-inc-oncocheck.jpg',
  },
  {
    slug: 'amber-road-miner-report',
    name: '앰버로드 (마이너리포트)',
    tagline: {
      ko: '현장 전문가들이 만든 제조 공정 최적화 AI 솔루션',
      en: 'Manufacturing process optimization AI solution created by field experts',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'amber-road-miner-report.jpg',
  },
  {
    slug: 'lucentblock-sou',
    name: '루센트블록 (소유)',
    tagline: {
      ko: '부동산을 증권화해 소액 단위로 거래할 수 있는 토큰증권(STO) 플랫폼',
      en: 'Token Securities (STO) platform that securitizes real estate and allows trading in small amounts',
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'lucentblock-sou.jpg',
  },
  {
    slug: 'bonjac-selvatico',
    name: '본작 (셀바티코)',
    tagline: {
      ko: '프랑스 4대 조향회사와 다이렉트 개발 및 제조한 니치향료 솔루션',
      en: 'Niche fragrance solution developed and manufactured directly with France’s top four perfume companies',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bonjac-selvatico.jpg',
  },
  {
    slug: 'motiv-intelligence-onnuri-dmc',
    name: '모티브인텔리전스 (온누리DMC)',
    tagline: {
      ko: 'Software Development',
      en: 'Software Development',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'motiv-intelligence-onnuri-dmc.jpg',
  },
  {
    slug: 'ninehire-hackit',
    name: '나인하이어',
    tagline: {
      ko: '공고 작성부터 최종 합격까지 여러 구인구직 채널에서 진행되는 채용의 전 과정을 한 곳에 모아 관리할 수 있는 채용 관리 솔루션',
      en: 'A recruitment management solution that allows you to collect and manage the entire recruitment process across multiple job search channels in one place, from posting an announcement to final acceptance.',
    },
    category: 'hrtech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'ninehire-hackit.jpg',
  },
  {
    slug: 'eargada-nadio',
    name: '이어가다',
    tagline: {
      ko: '내가 쓴 글을 내 목소리로 들려주고 공유하는 숏폼 힐링 오디오 - 나디오',
      en: 'A short-form healing audio that lets you hear and share what you wrote in your own voice - Nadio',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'eargada-nadio.jpg',
  },
  {
    slug: 'metarpas',
    name: '메타파스',
    tagline: {
      ko: '태양광발전소의 검사/관리를 위한 항공 열화상 플랫폼',
      en: 'Aerial thermal imaging platform for inspection/management of solar power plants',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'metarpas.jpg',
  },
  {
    slug: 'better-monday-korea',
    name: '베러먼데이코리아',
    tagline: {
      ko: '직장인들을 위한 온&오프라인 통합 커뮤니티 플랫폼, 베러먼데이',
      en: 'Better Monday, an integrated online and offline community platform for office workers',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'better-monday-korea.jpg',
  },
  {
    slug: 'elroilab',
    name: '엘로이랩',
    tagline: {
      ko: '초분광 영상 처리 기술과 AI 기술을 결합한 솔루션, 스펙트럴에이아이',
      en: 'Spectral AI, a solution that combines hyperspectral image processing technology and AI technology',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'elroilab.jpg',
  },
  {
    slug: 'vi-korea-cays',
    name: '브이아이코리아',
    tagline: {
      ko: '실시간 견적 및 칼선 제공의 맞춤형 패키지 박스 제작 서비스',
      en: 'Customized package box production service with real-time quotation and cutting lines',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'vi-korea-cays.jpg',
  },
  {
    slug: 'yol-cargo',
    name: '욜카고',
    tagline: {
      ko: '수출입기업에게 빠르고 저렴한 국제운송을 제공하는 플랫폼',
      en: 'A platform that provides fast and inexpensive international transportation to import and export companies.',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'yol-cargo.jpg',
  },
  {
    slug: 'tutoring',
    name: '튜터링',
    tagline: {
      ko: '튜더링 (언제 어디서나 실시간으로 글로벌 개인 튜터를 연결하여 실시간 스피킹 레슨을 제공하는 교육 플랫폼)',
      en: 'Tudoring (an education platform that provides real-time speaking lessons by connecting global personal tutors in real time, anytime, anywhere)',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'tutoring.jpg',
  },
  {
    slug: 'brots',
    name: '브로츠',
    tagline: {
      ko: '음악을 발견하고 지역 아티스트의 공연 정보를 제공하는 틴더 스타일의 음악 앱',
      en: 'A Tinder-style music app for music discovery and performance information from local artists.',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'brots.jpg',
  },
  {
    slug: 'thinggotingoland',
    name: '틴고랜드',
    tagline: {
      ko: 'Energy',
      en: 'Energy',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'thinggotingoland.jpg',
  },
  {
    slug: 'onesoftdigm',
    name: '원소프트다임',
    tagline: {
      ko: 'Medicaltech',
      en: 'Medicaltech',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'onesoftdigm.jpg',
  },
  {
    slug: 'specter',
    name: '스펙터',
    tagline: {
      ko: '지원자의 평판을 조회할 수 있는 평판 조회 플랫폼',
      en: 'Reputation inquiry platform where you can check the reputation of applicants',
    },
    category: 'hrtech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'specter.jpg',
  },
  {
    slug: 'softlanders',
    name: '소프트랜더스',
    tagline: {
      ko: '임직원 해외파견을 위한 해외사업지원 서비스 글로벌 리로케이션 플랫폼, 소프트랜더스',
      en: 'Soft Landers, a global relocation platform that provides overseas business support services for dispatching employees overseas',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'softlanders.jpg',
  },
  {
    slug: 'moverse',
    name: '무버스',
    tagline: {
      ko: '메타버스와 버추얼휴먼을 위한 3D 모션 창작과 공급 솔루션',
      en: '3D motion creation and supply solution for metaverse and virtual humans',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'moverse.jpg',
  },
  {
    slug: 'logstack',
    name: '로그스택',
    tagline: {
      ko: '실시간 회계부정 탐지를 위한 내부통제 솔루션 전문기업',
      en: 'Internal control solution specialist for real-time accounting fraud detection',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'logstack.jpg',
  },
  {
    slug: 'xcrew',
    name: '엑스크루',
    tagline: {
      ko: '퇴근 후의 여가 시간을 특별하게 만들어주는 액티비티 플랫폼',
      en: 'An activity platform that makes leisure time after work special',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'xcrew.jpg',
  },
  {
    slug: 'villagebaby',
    name: '빌리지베이비',
    tagline: {
      ko: '한국, 베트남, 인도네시아, 태국 등 아시아 밀레니얼 부모를 사로잡은 임신·육아 정보 플랫폼',
      en: 'Pregnancy and childcare information platform that captivates Asian millennial parents in Korea, Vietnam, Indonesia, and Thailand',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'villagebaby.jpg',
  },
  {
    slug: 'reharvest',
    name: '리하베스트',
    tagline: {
      ko: 'Energy',
      en: 'Energy',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'reharvest.jpg',
  },
  {
    slug: 'kitchen-in-the-lab',
    name: '키친인더랩',
    tagline: {
      ko: '프롬쉐프 (레스토랑에서 먹었던 맛 그래로 퀄리티 높은 요리를 간편하게 레토르 형식으로 만드는 회사)',
      en: 'From Chef (a company that makes high-quality dishes with the same taste as those eaten at restaurants in a simple retort format)',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kitchen-in-the-lab.jpg',
  },
  {
    slug: 'ondo',
    name: '온도',
    tagline: {
      ko: 'Fashion',
      en: 'Fashion',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'ondo.jpg',
  },
  {
    slug: 'personal-ai',
    name: '퍼스널에이아이',
    tagline: {
      ko: '마이디 (내 금융 데이터를 관리하고 거래하는 마이데이터 플랫폼)',
      en: 'MyD (My Data Platform to manage and trade my financial data)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'personal-ai.png',
  },
  {
    slug: 'casting',
    name: '캐스팅',
    tagline: {
      ko: '다양한 분야의 인플루언서들이 팬들과 1:1로 소통할 수 있는 플랫폼',
      en: 'A platform where influencers in various fields can communicate 1:1 with fans',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'casting.jpg',
  },
  {
    slug: 'softment',
    name: '소프트먼트',
    tagline: {
      ko: 'Human Resource',
      en: 'Human Resources',
    },
    category: 'hrtech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'softment.png',
  },
  {
    slug: 'cloa',
    name: '클로아',
    tagline: {
      ko: '클로아 (방대한 데이터를 실시간으로 처리하는데 최적화된 데이터 파이프라인 솔루션)',
      en: 'Cloa (data pipeline solution optimized for processing massive amounts of data in real time)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'cloa.jpg',
  },
  {
    slug: 'octatco',
    name: '옥타코',
    tagline: {
      ko: 'E-Commerce',
      en: 'E-Commerce',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'octatco.jpg',
  },
  {
    slug: 'rawlabs',
    name: '로랩스 (에어서플라이)',
    tagline: {
      ko: '에어서플라이 (기업의 전자결재, 비품 가격비교를 제공하는 SaaS형 구매관리솔루션)',
      en: 'Air Supply (SaaS-type purchase management solution that provides corporate electronic payment and equipment price comparison)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'rawlabs.jpg',
  },
  {
    slug: 'peopet',
    name: '페오펫',
    tagline: {
      ko: '페오펫 (간편 모바일 반려동물등록 서비스)',
      en: 'Peopet (simple mobile pet registration service)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'peopet.jpg',
  },
  {
    slug: 'crepass',
    name: '크레파스솔루션',
    tagline: {
      ko: '청년5.5 (대안신용평가를 통한 새로운 P2P 투자 플랫폼)',
      en: 'Youth 5.5 (new P2P investment platform through alternative credit rating)',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'crepass.jpg',
  },
  {
    slug: 'edgecross',
    name: '엣지크로스',
    tagline: {
      ko: 'AIoT 기술 기반 스마트 머신 전환 전문 기업. 기계 장비 원격 모니터링, 제어, 관제 솔루션 제공.',
      en: 'A company specializing in smart machine conversion based on AIoT technology. Providing remote monitoring, control, and management solutions for mechanical equipment.',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'edgecross.jpg',
  },
  {
    slug: 'veluga',
    name: '벨루가',
    tagline: {
      ko: '벨루가 (맥주 정기배송서비스)',
      en: 'Beluga (regular beer delivery service)',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'veluga.jpg',
  },
  {
    slug: 'perfitt',
    name: '펄핏',
    tagline: {
      ko: '펄핏 (신발 사이즈 추천 솔루션)',
      en: 'Pearl Fit (shoe size recommendation solution)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'perfitt.jpg',
  },
  {
    slug: 'knowre',
    name: '노리',
    tagline: {
      ko: '노리 (인공지능 기반 개인화 수학교육 서비스)',
      en: 'Nori (artificial intelligence-based personalized math education service)',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'knowre.jpg',
  },
  {
    slug: 'weplanet',
    name: '위플래닛',
    tagline: {
      ko: '모바일, 웹 서비스 프로토타입 개발 전문 서비스 및 자체 커머스 운영',
      en: 'Mobile and web service prototype development professional services and own commerce operation',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'weplanet.jpg',
  },
  {
    slug: 'tapjoy-5rocks',
    name: '탭조이 (파이브락스)',
    tagline: {
      ko: '모바일 광고, 시장 조사 및 앱 수익화 솔루션',
      en: 'Mobile advertising, market research and app monetization solutions',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'tapjoy-5rocks.jpg',
  },
  {
    slug: 'zoyi',
    name: '조이코퍼레이션',
    tagline: {
      ko: '자체 개발 센서를 통한 오프라인 매장 방문자 데이터 취합 및 분석 인사이트 제공 서비스',
      en: 'Offline store visitor data collection and analysis insight service through self-developed sensors',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'zoyi.jpg',
  },
  {
    slug: 'landing-international',
    name: '랜딩인터내셔널',
    tagline: {
      ko: '뷰티 B2B 유통 (한국 뷰티 브랜드 미국 B2B 유통 서비스)',
      en: 'Beauty B2B distribution (Korean beauty brand US B2B distribution service)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'landing-international.jpg',
  },
  {
    slug: 'chartmetric',
    name: '차트메트릭',
    tagline: {
      ko: '차트메트릭 (빅데이터 음악 분석 서비스)',
      en: 'Chartmetric (big data music analysis service)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'chartmetric.jpg',
  },
  {
    slug: 'treeplanet',
    name: '트리플래닛',
    tagline: {
      ko: 'Agritech',
      en: 'Agritech',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'treeplanet.jpg',
  },
  {
    slug: 'piquant',
    name: '파이퀀트',
    tagline: {
      ko: 'Medicaltech',
      en: 'Medicaltech',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'piquant.jpg',
  },
  {
    slug: 'lockin-company',
    name: '락인컴퍼니',
    tagline: {
      ko: '모바일 애플리케이션 보안 전문 기업',
      en: 'Mobile application security specialist company',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'lockin-company.jpg',
  },
  {
    slug: 'stayes',
    name: '스테이즈',
    tagline: {
      ko: 'Real Estate',
      en: 'Real Estate',
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'stayes.jpg',
  },
  {
    slug: 'pentapress',
    name: '펜타프레스',
    tagline: {
      ko: '국내외 포토 서비스 플랫폼을 운영하는 국내 최초 글로벌 사진통신사',
      en: 'Korea’s first global photo communication company that operates domestic and international photo service platforms',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'pentapress.jpg',
  },
  {
    slug: 'ekne',
    name: '에크네',
    tagline: {
      ko: '창작자와 제작자를 혁신적으로 연결하는 스토리콘텐츠 플랫폼',
      en: 'A story content platform that innovatively connects creators and producers',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'ekne.jpg',
  },
  {
    slug: 'topolog',
    name: '토폴로그',
    tagline: {
      ko: 'B2B의 미래 파트너십을 위한 혁신적 기업 데이터 플랫폼!',
      en: 'An innovative corporate data platform for future B2B partnerships!',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'topolog.jpg',
  },
  {
    slug: 'hiritsoft',
    name: '히릿소프트',
    tagline: {
      ko: '노코드 혁명의 선두주자, 히릿소프트의 \'메이더\': 중소기업 디지털 전환 가속화',
      en: 'Leader of the no-code revolution, Hiritsoft’s ‘Mader’: Accelerating digital transformation of small and medium-sized businesses',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'hiritsoft.jpg',
  },
  {
    slug: 'mangoplate',
    name: '망고플레이트',
    tagline: {
      ko: '사용자의 객관적인 리뷰를 기반으로 한 위치 기반 맛집 검색 및 추천 서비스',
      en: 'Location-based restaurant search and recommendation service based on users’ objective reviews',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'mangoplate.jpg',
  },
  {
    slug: 'splab',
    name: '스플랩',
    tagline: {
      ko: '네트워킹의 혁신! 온·오프라인 행사 네트워킹을 위한 \'스페이스\'로 연결의 새 시대를 열다.',
      en: 'Innovation in networking! Opening a new era of connection with ‘Space’ for online and offline event networking.',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'splab.jpg',
  },
  {
    slug: 'look-insight-yakollyeo',
    name: '룩인사이트 (약올려)',
    tagline: {
      ko: '의약품 B2B 전자상거래 플랫폼 \'약올려\'를 운영하는 기업',
      en: 'A company that operates the pharmaceutical B2B e-commerce platform ‘Yakollyeo’',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'look-insight-yakollyeo.jpg',
  },
  {
    slug: 'kzone',
    name: '케이존',
    tagline: {
      ko: '케이존, 국내 첫 미국 아마존 SPN 지정 역물류 SW 스타트업!',
      en: 'K-Zone, the first reverse logistics software startup in Korea to be designated as SPN by the US Amazon!',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kzone.jpg',
  },
  {
    slug: 'fluentt',
    name: '플루언트',
    tagline: {
      ko: '플루언트, 3D 아바타 혁신의 선봉자로 중기부 팁스에 선정!',
      en: '',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'fluentt.jpg',
  },
  {
    slug: 'vetflux',
    name: '벳플럭스',
    tagline: {
      ko: 'AI 챗봇 \'늘펫플러스\'로 동물병원 업무 자동화',
      en: 'Automation of animal hospital work with AI chatbot ‘Neul Pet Plus’',
    },
    category: 'saas',
    entity: 'korea',
    country: 'KR',
    logoFile: 'vetflux.jpg',
  },
  {
    slug: 'ggq',
    name: '지지큐',
    tagline: {
      ko: 'AI로 게임 전략과 플레이 기법을 코칭하는 스타트업.',
      en: 'A startup that coaches game strategies and play techniques using AI.',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'ggq.jpg',
  },
  {
    slug: 'billyo',
    name: '빌리오',
    tagline: {
      ko: '크리에이터의 촬영 및 연습 공간 예약을 전문으로 하는 버티컬 예약 앱 서비스',
      en: 'Vertical reservation app service specializing in booking filming and practice spaces for creators',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'billyo.jpg',
  },
  {
    slug: 'amondy',
    name: '아몬디',
    tagline: {
      ko: '상담에 집중, 번거로운 행정 업무는 우리에게 맡기세요',
      en: 'Focus on consultation, leave the cumbersome administrative work to us.',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'amondy.jpg',
  },
  {
    slug: 'growth-fit',
    name: '그로스핏',
    tagline: {
      ko: '전문가들의 협업을 위한 애널리틱스 연계 협업툴로 업무 효율 극대화',
      en: 'Maximize work efficiency with analytics-linked collaboration tools for collaboration between experts',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'growth-fit.jpg',
  },
  {
    slug: 'iclave',
    name: '아이클레이브',
    tagline: {
      ko: '아이클레이브는 AI를 활용한 이커머스 운영 자동화 SaaS 솔루션을 제공하는 선도 기업입니다.',
      en: 'iCave is a leading company that provides SaaS solutions for e-commerce operation automation using AI.',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'iclave.jpg',
  },
  {
    slug: 'mask-moments',
    name: '마스크모먼트',
    tagline: {
      ko: '마스크모먼트는 미국 기반의 피부 관리 전자 상거래 스타트업으로, 2018년에 소피아 홍 CEO에 의해 창립되었습니다.',
      en: 'Maskmoment is a US-based skin care e-commerce startup founded in 2018 by CEO Sophia Hong.',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'mask-moments.jpg',
  },
  {
    slug: 'moonriver',
    name: '문리버',
    tagline: {
      ko: 'E-Commerce',
      en: 'E-Commerce',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'moonriver.jpg',
  },
  {
    slug: 'seoul-bund',
    name: '서울번드',
    tagline: {
      ko: '서울번드 (동아시아 리빙디자인 전문몰)',
      en: 'Seoul Bund (East Asian living design specialty mall)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'seoul-bund.jpg',
  },
  {
    slug: 'shark-market',
    name: '샤크마켓',
    tagline: {
      ko: '베트남 시장을 겨냥한 신선식품 배송 서비스',
      en: 'Fresh food delivery service targeting the Vietnamese market',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'shark-market.jpg',
  },
  {
    slug: 'gmg',
    name: '지엠지',
    tagline: {
      ko: 'Real Estate',
      en: 'Real Estate',
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'gmg.jpg',
  },
  {
    slug: 'lablaco',
    name: '라블라코',
    tagline: {
      ko: '패션 브랜드간의 온라인, 오프라인, 물류를 결합하여 소비자와 브랜드, 소매업체 간의 관계를 재정의하는 원스톱 옴니채널 솔루션을 제공',
      en: 'Provides a one-stop omnichannel solution that redefines the relationship between consumers, brands, and retailers by combining online, offline, and logistics between fashion brands.',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'lablaco.jpg',
  },
  {
    slug: 'oinng-pickit',
    name: '오닝 (픽잇)',
    tagline: {
      ko: 'Entertainment',
      en: 'Entertainment',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'oinng-pickit.jpg',
  },
  {
    slug: 'tkit',
    name: '티킷',
    tagline: {
      ko: '티킷 (공연 초대권 / 전자 티켓 서비스)',
      en: 'Ticket (performance invitation / electronic ticket service)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'tkit.jpg',
  },
  {
    slug: 'a-impact',
    name: '에이임팩트',
    tagline: {
      ko: 'Agritech',
      en: 'Agritech',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'a-impact.jpg',
  },
  {
    slug: 'curiochips',
    name: '큐리오칩스',
    tagline: {
      ko: 'Medicaltech',
      en: 'Medicaltech',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'curiochips.jpg',
  },
  {
    slug: 'abuhakim',
    name: '아부하킴',
    tagline: {
      ko: '한국 제조사들이 중동 소비자들에게 직접 제품을 판매하고 마케팅할 수 있도록 현지 언어, 문화, 결제, 배송에 최적화된 솔루션을 제공.',
      en: 'Provides solutions optimized for local language, culture, payment, and delivery so that Korean manufacturers can sell and market products directly to Middle Eastern consumers.',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'abuhakim.jpg',
  },
  {
    slug: 'inpock',
    name: '인포크',
    tagline: {
      ko: '인포크 (인플루언서 기반 소셜커머스)',
      en: 'Infork (Influencer-based social commerce)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'inpock.jpg',
  },
  {
    slug: 'vlogr',
    name: '브이로거',
    tagline: {
      ko: '브이로거 (영상 편집 애플리케이션)',
      en: 'Vlogger (video editing application)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'vlogr.jpg',
  },
  {
    slug: 'fluid',
    name: '플루이드',
    tagline: {
      ko: '플루이드 (단순 광고와 기존의 유료 구독 사이트를 벗어나, 참신한 수익 모델이 필요한 컨텐츠 생산자를 위한 솔루션)',
      en: 'Fluid (a solution for content producers who need a novel revenue model beyond simple advertising and existing paid subscription sites)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'fluid.jpg',
  },
  {
    slug: 'zhenhub',
    name: '젠허브',
    tagline: {
      ko: '젠허브 (클라우드 기반 물류 플랫폼)',
      en: 'ZenHub (cloud-based logistics platform)',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'zhenhub.jpg',
  },
  {
    slug: 'genecast',
    name: '진캐스트',
    tagline: {
      ko: 'Medicaltech',
      en: 'Medicaltech',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'genecast.jpg',
  },
  {
    slug: 'profound',
    name: '프로파운드',
    tagline: {
      ko: '프로파운드 (글로벌 비즈니스 전문가 연결 플랫폼)',
      en: 'Profound (global business expert connection platform)',
    },
    category: 'hrtech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'profound.jpg',
  },
  {
    slug: 'swingvy',
    name: '스윙비',
    tagline: {
      ko: '스윙비 (동남아 소기업 클라우드 인사관리 소프트웨어)',
      en: 'Swingbee (Southeast Asian small business cloud human resource management software)',
    },
    category: 'hrtech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'swingvy.jpg',
  },
  {
    slug: 'kooding',
    name: '쿠딩',
    tagline: {
      ko: 'Fashion',
      en: 'Fashion',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kooding.jpg',
  },
  {
    slug: 'jocoos',
    name: '요쿠스',
    tagline: {
      ko: 'JPlayer (실시간 스트리밍 솔루션 및 트랜스 코더로 구성된 비디오 기술을 제공), SURT (모바일 오디션 플랫폼)',
      en: 'JPlayer (provides video technology consisting of a live streaming solution and transcoder), SURT (mobile audition platform)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'jocoos.jpg',
  },
  {
    slug: 'water-strider',
    name: '워터스트라이더',
    tagline: {
      ko: '3D 근접 공간 감지 원천 기술 기반 비접촉 솔루션 개발사',
      en: 'Non-contact solution developer based on 3D proximity space sensing original technology',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'water-strider.jpg',
  },
  {
    slug: 'slab-asia',
    name: '에스랩아시아',
    tagline: {
      ko: '아시아를 대표하는 의약품 콜드체인 서비스 기업입니다',
      en: 'Asia\'s leading pharmaceutical cold chain service company.',
    },
    category: 'mobility',
    entity: 'korea',
    country: 'KR',
    logoFile: 'slab-asia.jpg',
  },
  {
    slug: 'swatchon',
    name: '스와치온',
    tagline: {
      ko: '패션 소재 생산자와 브랜드를 연결해 효율적인 소재 공급 관리를 돕는 온라인 플랫폼',
      en: 'An online platform that connects fashion material producers and brands to help manage material supply efficiently.',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'swatchon.png',
  },
  {
    slug: 'bringko',
    name: '브링코',
    tagline: {
      ko: '브링코 (한국의 유명 오픈마켓, 대형쇼핑몰, 아이템몰을 한꺼번에 해외에서도 편리하게 구매가능한 아이템 몰)',
      en: 'Bringco (Item mall where you can conveniently purchase Korea’s famous open market, large shopping mall, and item mall all at once from overseas)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bringko.jpg',
  },
  {
    slug: 'xsync',
    name: '엑씽크',
    tagline: {
      ko: 'xSync (현장에서 참가자와 소통할 수 있는 이벤트 매니지먼트 플랫폼)',
      en: 'xSync (event management platform that allows you to communicate with participants on site)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'xsync.jpg',
  },
  {
    slug: 'balaan',
    name: '발란',
    tagline: {
      ko: '국내에서 가장 많은 브랜드 상품을 유통하는 명품 판매 플랫폼',
      en: 'Luxury goods sales platform that distributes the largest number of branded products in Korea',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'balaan.jpg',
  },
  {
    slug: 'xbrain',
    name: '엑스브레인',
    tagline: {
      ko: '다리아 (클라우드기반 머신러닝 모델링 어시스턴트 소프트웨어)',
      en: 'Daria (cloud-based machine learning modeling assistant software)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'xbrain.jpg',
  },
  {
    slug: 'fasket',
    name: '패스켓',
    tagline: {
      ko: '반려동물 온오프라인 통합 플랫폼',
      en: 'Pet online/offline integrated platform',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'fasket.jpg',
  },
  {
    slug: 'collegenie-ai',
    name: '컬리지니에이아이',
    tagline: {
      ko: 'SaaS',
      en: 'SaaS',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'collegenie-ai.jpg',
  },
  {
    slug: 'noda-labs',
    name: '노다랩',
    tagline: {
      ko: 'Data Analytics',
      en: 'Data Analytics',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'noda-labs.jpg',
  },
  {
    slug: 'bootalkuiti',
    name: '부톡',
    tagline: {
      ko: 'AI 기반 부동산 매물 추천 서비스를 제공하는 프롭테크 스타트업',
      en: 'Proptech startup providing AI-based real estate listing recommendation service',
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bootalkuiti.jpg',
  },
  {
    slug: 'careerday-1',
    name: '커리어데이',
    tagline: {
      ko: 'HR tech',
      en: 'HR tech',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'careerday-1.jpg',
  },
  {
    slug: 'standingtall',
    name: '스탠딩톨',
    tagline: {
      ko: '척추보조기 \'플렉스파인\'으로 국내와 해외 시장에서 활발한 경쟁을 펼치고 있다.',
      en: 'The company is actively competing in domestic and overseas markets with its spinal brace \'Flexfine\'.',
    },
    category: 'bio',
    entity: 'korea',
    country: 'KR',
    logoFile: 'standingtall.jpg',
  },
  {
    slug: 'instant-tattoo-1',
    name: '인스턴트타투',
    tagline: {
      ko: '인스턴트타투™는 자연스럽고 아름다운 시티라이프를 제안하는 템포러리 타투 브랜드입니다.',
      en: 'Instant Tattoo™ is a temporary tattoo brand that offers a natural and beautiful city life.',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'instant-tattoo-1.jpg',
  },
  {
    slug: 'starteacher-tevaluewise',
    name: '별별선생',
    tagline: {
      ko: '강사 평가 서비스를 제공하는 스타트업 TEvalueWise社 의 온라인 플랫폼',
      en: 'Online platform of TEvalueWise, a startup that provides instructor evaluation services',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'starteacher-tevaluewise.jpg',
  },
  {
    slug: 'tella',
    name: '텔라',
    tagline: {
      ko: 'Edutech',
      en: 'Edutech',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'tella.jpg',
  },
  {
    slug: 'xelin',
    name: '세린',
    tagline: {
      ko: '마이크로다이싱 (열을 활용한 레이저 기술의 문제점을 보완한 초미세 레이저 커팅 기술 개발)',
      en: 'Micro dicing (development of ultra-fine laser cutting technology that complements the problems of laser technology using heat)',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'xelin.jpg',
  },
  {
    slug: 'spiceware',
    name: '스파이스웨어',
    tagline: {
      ko: '스파이스웨어 (클라우드 데이터 암호화 솔루션)',
      en: 'Spiceware (cloud data encryption solution)',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'spiceware.jpg',
  },
  {
    slug: 'whelp',
    name: '웰프',
    tagline: {
      ko: '세일즈 및 고객관리 직원들이 서로 다른 대화 채널을 사용하는 고객들과 한 곳에서 소통할 수 있게 도와주는 플랫폼',
      en: 'A platform that helps sales and customer management employees communicate with customers using different conversation channels in one place.',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'whelp.jpg',
  },
  {
    slug: 'paywatch-global',
    name: '페이워치',
    tagline: {
      ko: '페이워치 (사장님/알바생을 위한 출퇴근 인증,전자근로계약, 당일급여정산 서비스)',
      en: 'Paywatch (commuting authentication, electronic employment contract, same-day salary settlement service for bosses/part-time workers)',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'paywatch-global.jpg',
  },
  {
    slug: 'bitbyte',
    name: '비트바이트',
    tagline: {
      ko: '플레이키보드 (캐릭터, 일러스트 등 다양한 콘텐츠로 스마트폰 키보드를 꾸밀 수 있는 앱)',
      en: 'Play Keyboard (an app that allows you to decorate your smartphone keyboard with various content such as characters and illustrations)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'bitbyte.jpg',
  },
  {
    slug: 'featuring',
    name: '피처링',
    tagline: {
      ko: 'SNS 인플루언서의 ‘진짜\' 영향력을 측정해주는 플랫폼',
      en: 'A platform that measures the ‘real’ influence of SNS influencers',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'featuring.jpg',
  },
  {
    slug: 'smartjack',
    name: '스마트잭',
    tagline: {
      ko: '랩매니저 (물품/안전/행정/HR 관리 기능을 제공하는 연구실 토탈 관리 솔루션)',
      en: 'Lab Manager (laboratory total management solution providing product/safety/administrative/HR management functions)',
    },
    category: 'ai',
    entity: 'korea',
    country: 'KR',
    logoFile: 'smartjack.jpg',
  },
  {
    slug: 'activity-exchange',
    name: '액스(AX)',
    tagline: {
      ko: '전세계 현지 여행사를 위해 여행상품 퍼블리싱과 예약관리 솔루션을 개발하는 스타트업',
      en: 'A startup that develops travel product publishing and reservation management solutions for local travel agencies around the world.',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'activity-exchange.jpg',
  },
  {
    slug: 'global-bridge',
    name: '글로벌브릿지',
    tagline: {
      ko: 'Guardian RF SoC (IoT 및 ICT를 위한 무선 SoC 솔루션)',
      en: 'Guardian RF SoC (wireless SoC solution for IoT and ICT)',
    },
    category: 'security',
    entity: 'korea',
    country: 'KR',
    logoFile: 'global-bridge.jpg',
  },
  {
    slug: 'thirteenth-floor',
    name: '서틴스플로어',
    tagline: {
      ko: 'VR',
      en: 'VR',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'thirteenth-floor.jpg',
  },
  {
    slug: 'simple-kitchen-hat-company',
    name: '심플키친',
    tagline: {
      ko: '외식업 창업자들에게 주방공간과 시설을 제공해주고 다양한 비용을 공유함으로서 매출을 극대화 시켜주는 공유주방 플랫폼',
      en: 'A shared kitchen platform that maximizes sales by providing kitchen space and facilities to restaurant entrepreneurs and sharing various costs.',
    },
    category: 'proptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'simple-kitchen-hat-company.jpg',
  },
  {
    slug: 'fleapop',
    name: '플리팝',
    tagline: {
      ko: '러블리마켓 (10~20대 여성들을 위한 크로스오버 쇼핑채널)',
      en: 'Lovely Market (crossover shopping channel for women in their teens and twenties)',
    },
    category: 'commerce',
    entity: 'korea',
    country: 'KR',
    logoFile: 'fleapop.jpg',
  },
  {
    slug: 'emolize-payvil',
    name: '에몰라이즈',
    tagline: {
      ko: 'Fintech',
      en: 'Fintech',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'emolize-payvil.jpg',
  },
  {
    slug: 'kadho',
    name: '캐드호',
    tagline: {
      ko: '캐드호 (두뇌 훈련 커리큘럼 전문 기업으로 뇌 학습 효율 향상 주력)',
      en: 'CADHO (a company specializing in brain training curriculum, focusing on improving brain learning efficiency)',
    },
    category: 'other',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kadho.jpg',
  },
  {
    slug: 'the-clozet',
    name: '더클로젯컴퍼니',
    tagline: {
      ko: 'Fashion',
      en: 'Fashion',
    },
    category: 'consumer',
    entity: 'korea',
    country: 'KR',
    logoFile: 'the-clozet.jpg',
  },
  {
    slug: 'asian-boss',
    name: '아시안보스',
    tagline: {
      ko: '아시안보스 (아시아 전역의 최신 뉴스와 트랜드를 전세계에 전달하는 뉴미디어 기업으로 현재 유튜브 활동 중)',
      en: 'Asian Boss (a new media company that delivers the latest news and trends from across Asia to the world, currently active on YouTube)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'asian-boss.jpg',
  },
  {
    slug: 'kloser',
    name: '클로저',
    tagline: {
      ko: '클로저 (고객 채널 관리 플랫폼)',
      en: 'Closure (Customer Channel Management Platform)',
    },
    category: 'media',
    entity: 'korea',
    country: 'KR',
    logoFile: 'kloser.jpg',
  },
  {
    slug: 'queensbucket',
    name: '쿠엔즈버킷',
    tagline: {
      ko: '쿠엔즈버킷 참기름 (참기름)',
      en: 'Queen\'s Bucket Sesame Oil (Sesame Oil)',
    },
    category: 'agrifood',
    entity: 'korea',
    country: 'KR',
    logoFile: 'queensbucket.jpg',
  },
  {
    slug: 'paymonths',
    name: '페이먼스',
    tagline: {
      ko: '도매 사입도 후불로 페이먼스 후불 결제',
      en: 'Wholesale purchases are also made with deferred payment.',
    },
    category: 'fintech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'paymonths.jpg',
  },
  {
    slug: 'urbanbase',
    name: '어반베이스',
    tagline: {
      ko: 'VR',
      en: 'VR',
    },
    category: 'deeptech',
    entity: 'korea',
    country: 'KR',
    logoFile: 'urbanbase.jpg',
  },
];

export const portfolio: PortfolioCompany[] = [...globalAiLeaders, ...koreaCore, ...scrapedCompanies];

export const categoryLabel: Record<PortfolioCategory, { ko: string; en: string }> = {
  ai: { ko: 'AI', en: 'AI' },
  fintech: { ko: '핀테크', en: 'Fintech' },
  bio: { ko: '바이오·헬스케어', en: 'Bio & Healthcare' },
  mobility: { ko: '모빌리티', en: 'Mobility' },
  saas: { ko: 'SaaS', en: 'SaaS' },
  commerce: { ko: '커머스', en: 'Commerce' },
  hrtech: { ko: 'HR Tech', en: 'HR Tech' },
  agrifood: { ko: '푸드·애그리', en: 'Agrifood' },
  security: { ko: '보안', en: 'Security' },
  media: { ko: '미디어·엔터', en: 'Media & Entertainment' },
  consumer: { ko: '컨슈머', en: 'Consumer' },
  proptech: { ko: '프롭테크', en: 'PropTech' },
  deeptech: { ko: '딥테크', en: 'Deep Tech' },
  other: { ko: '기타', en: 'Other' },
};

export function getCategories() {
  const unique = new Set(portfolio.map((p) => p.category));
  return Array.from(unique);
}

export function getEntitySlugs() {
  const unique = new Set(portfolio.map((p) => p.entity));
  return Array.from(unique);
}
