// 자동 생성된 파일 — sparklabs.co.kr/kr/portfolio 스크래핑 결과
// 생성일: 2026-05-04

export interface ScrapedPortfolioCompany {
  slug: string;
  nameKo: string;
  nameEn: string;
  category: string;
  descriptionKo: string;
  logoFile: string;
}

export const scrapedPortfolio: ScrapedPortfolioCompany[] = [
  {
    slug: "wantedlab",
    nameKo: "원티드랩",
    nameEn: "WantedLab",
    category: "HRtech",
    descriptionKo: `원티드랩은 '우리 모두가 나답게 일하고 즐겁게 성장할 수 있도록 돕기'를 미션으로, AI 매칭 등 차별화된 기술과 데이터를 통해 개인화된 커리어 성장 기회를 제공하는 HR테크 업계 선도 기업이다.2015년 설립 이후…`,
    logoFile: "wantedlab.png",
  },
  {
    slug: "quadmedicine",
    nameKo: "쿼드메디슨",
    nameEn: "QuadMedicine",
    category: "Bio",
    descriptionKo: `쿼드메디슨은 경피로 전달이 가능한 백신의약품과 합성의약품, 진단의료기기까지 폭넓은 활용이 가능한 의료용 마이크로니들 플랫폼 기술을 보유한 기업이다. 기존의 피하주사제 또는 경구복용 의약품을 마이크로니들 플랫폼 기술을…`,
    logoFile: "quadmedicine.png",
  },
  {
    slug: "fescaro",
    nameKo: "페스카로",
    nameEn: "Fescaro",
    category: "Cybersecurity",
    descriptionKo: `페스카로(Fescaro)는 자율주행자동차, 커넥티드카 등 자동차에 실제 양산 적용될 수 있는 보안 기술을 개발하고 있는 자동차 보안 전문 스타트업이다. 자동차 전자식 제어기(ECU) 개발사 출신의 연구원들과 화이트해…`,
    logoFile: "fescaro.png",
  },
  {
    slug: "bemyfriends-co-ltd",
    nameKo: "비마이프렌즈 - 비스테이지(b.stage)",
    nameEn: "bemyfriends Co., Ltd.",
    category: "Commerce",
    descriptionKo: `IT기술의 전문성을 기반으로, 아티스트 및 브랜드에게 IP 사업을 용이하게 하고, 커머스 운영 및 판매/마케팅 등 비즈니스 서비스 토탈 솔루션 '비스테이지(b.stage)'를 제공하는 기업, '비마이프렌즈'.비마이프…`,
    logoFile: "bemyfriends-co-ltd.png",
  },
  {
    slug: "bitsensing",
    nameKo: "비트센싱",
    nameEn: "Bitsensing",
    category: "AI",
    descriptionKo: `비트센싱은 RADAR 기술을 ITS, ADAS 그리고 자율주행 센서에 접목시켜 다가올 자율주행 시대에 안전한 도로 기반을 만들고자 한다. 현재 레이더 시스템 설계, 하드웨어, 소프트웨어까지 전체 레이더 기술 체인에 …`,
    logoFile: "bitsensing.jpg",
  },
  {
    slug: "gint",
    nameKo: "긴트",
    nameEn: "Gint",
    category: "Hardware",
    descriptionKo: `"긴트는 Ag-Tech 기술을 바탕으로 노지 농업의 첨단화를 추구하는 기업이다.긴트가 2022년에 출시한 자율주행 키트 '플루바 오토(PLUVA auto)'는 국내외 주요 브랜드의 트랙터, 이앙기, 승용관리기에 자유…`,
    logoFile: "gint.png",
  },
  {
    slug: "equal-table-inc",
    nameKo: "주식회사 이퀄테이블",
    nameEn: "Equal Table Inc.",
    category: "AI",
    descriptionKo: `주식회사 이퀄테이블은 AI 기반의 커피 산업 특화 MRV 자동화 시스템을 개발해, 기업이 커피 밸류체인의 탄소배출을 정량화하고 검증 가능한 형태로 관리할 수 있도록 돕는 혁신 스타트업입니다.전 세계적으로 환경 규제가…`,
    logoFile: "equal-table-inc.png",
  },
  {
    slug: "danstruct-co-ltd",
    nameKo: "주식회사 댄스트럭트",
    nameEn: "Danstruct Co., Ltd.",
    category: "Entertainment",
    descriptionKo: `댄스트럭트는 모션캡처와 편집 파이프라인, 그리고 유통 플랫폼을 기반으로 인간 움직임을 표준화된 3D 모션 데이터(FBX) 로 제작·가공·판매합니다. XSTAGE는 모션을 탐색·프리뷰할 수 있는 스토어 환경을 제공하며…`,
    logoFile: "danstruct-co-ltd.png",
  },
  {
    slug: "spring-again-co-ltd",
    nameKo: "주식회사 스프링어게인",
    nameEn: "Spring Again Co., Ltd.",
    category: "Platform",
    descriptionKo: `주식회사 스프링어게인이 운영하는 '나나스'는 초고령화 사회 속에서 거동이 어려운 시니어를 위한 B2B2C 방문 솔루션을 제공하는 기업입니다. 요양시설 단체 방문부터 실버타운, 아파트 커뮤니티, 가정 방문까지 서비스 …`,
    logoFile: "spring-again-co-ltd.png",
  },
  {
    slug: "bueno-company-co-ltd",
    nameKo: "(주)부에노컴퍼니",
    nameEn: "Bueno Company Co., Ltd.",
    category: "AI",
    descriptionKo: `부에노컴퍼니는 유통·리테일 매장의 홍보 효율성과 브랜드 일관성을 동시에 향상시키며, 오프라인 매장의 디지털 마케팅 전환을 지원하는 솔루션 ‘템플리(temply)’를 운영하고 있습니다.템플리는 반복적이고 시간이 많이 …`,
    logoFile: "bueno-company-co-ltd.png",
  },
  {
    slug: "polymerize-korea-llc",
    nameKo: "폴리머라이즈코리아유한회사",
    nameEn: "Polymerize Korea LLC",
    category: "Deep tech",
    descriptionKo: `폴리머라이즈는 기업의 연구개발을 더 빠르고 효율적으로 만드는 AI 기반 플랫폼입니다.기업 내부에 흩어져 있는 실험 데이터를 하나로 연결하고 체계적으로 정리하여, AI를 통해 다음 실험 방향을 제안하고 결과를 예측합니…`,
    logoFile: "polymerize-korea-llc.png",
  },
  {
    slug: "skylabs",
    nameKo: "스카이랩스",
    nameEn: "SkyLabs",
    category: "AI",
    descriptionKo: `스카이랩스는 AI 기반 헬스케어 플랫폼 기업으로, 만성질환 예방을 위한 건강 모니터링 서비스와 환자의 생체 데이터를 수집, 분석하여 개인 맞춤형 건강관리 솔루션을 제공합니다. 특히 사용자 조작없이 연속적으로 건강 모…`,
    logoFile: "skylabs.png",
  },
  {
    slug: "sparkplus",
    nameKo: "스파크플러스",
    nameEn: "sparkplus",
    category: "Proptech",
    descriptionKo: `스파크플러스는 모든 기업의 오피스 문제를 쉽고 빠르게 해결하고 본업에 집중할 수 있도록 만드는 것을 목표로 설립된 공유 오피스 기업이다. 2016년 11월 역삼 아주빌딩에 1호점을 시작으로 지난 22년 말까지 서울과…`,
    logoFile: "sparkplus.png",
  },
  {
    slug: "muzlive",
    nameKo: "뮤즈라이브",
    nameEn: "Muzlive",
    category: "Entertainment",
    descriptionKo: `"뮤즈라이브는 혁신적인 아이디어와 IT 기술의 집약을 통해 새로운 근거리통신 방식인 EUC(암호화초음파통신)을 개발하면서 스마트 기기에서 구동되는 실물 음반매체인 키트(KiT)를 2017년 선보였다. 키트는 음원 스…`,
    logoFile: "muzlive.png",
  },
  {
    slug: "queen-live-queen-of-shopping",
    nameKo: "퀸라이브 (쇼핑의 여왕)",
    nameEn: "Queen Live (QUEEN OF SHOPPING)",
    category: "E-commerce",
    descriptionKo: `퀸라이브는 2021년에 설립된 여성 패션 전문 라이브쇼핑 플랫폼으로, 대표 윤정탁은 이 앱을 통해 4050 여성들을 위한 최신 패션 트렌드와 스타일을 소개하며, 다양한 라이브 커머스 서비스를 제공합니다. 혁신적인 서…`,
    logoFile: "queen-live-queen-of-shopping.jpg",
  },
  {
    slug: "ssenstone",
    nameKo: "센스톤",
    nameEn: "Ssenstone",
    category: "Cybersecurity",
    descriptionKo: `센스톤은 글로벌 무대에서 최고 성적을 이뤄내며 인증 보안의 차세대 패러다임을 선도하는 기업으로, 기관 및 기업은 물론 일상 생활을 더 쉽고 빠르고 안전하게 연결하기 위한 인증보안 기술을 개발한다.'OTAC Token…`,
    logoFile: "ssenstone.png",
  },
  {
    slug: "reco",
    nameKo: "리코",
    nameEn: "RECO",
    category: "Sustainability",
    descriptionKo: `리코는 배출 환경 개선부터 자원순환까지 최적의 폐기물 솔루션을 제공하는 기업이다. 2020년 정식 런칭된 폐기물 수집운반 토탈 서비스 '업박스(UpBox)'는 기업형 폐기물 수집운반 토탈 서비스로, 사업장의 배출 환…`,
    logoFile: "reco.png",
  },
  {
    slug: "wave-corp",
    nameKo: "웨이브코퍼레이션",
    nameEn: "WAVE Corp.",
    category: "Entertainment",
    descriptionKo: `"웨이브코퍼레이션은 '세상에서 가장 놀기 좋은 공간을 만든다'는 비전을 바탕으로 사람들이 오프라인에서 어울리며 하는 행위들을 가상의 공간에서 쉽게 행할 수 있도록 돕는다.친구와 영상통화를 하면서 게임, 콘텐츠를 함께…`,
    logoFile: "wave-corp.jpg",
  },
  {
    slug: "doubleme",
    nameKo: "더블미",
    nameEn: "DoubleMe",
    category: "AR",
    descriptionKo: `더블미는 2015년 3월에 김희관(현 대표이사), Michael Kuzynski(현 최고운영이사), 김희영(현 재무이사)가 공동 창업한 후, 스파크랩 액셀러레이터 5기 및 삼성 C-Lab을 거쳐 성장해 왔다. 기존의…`,
    logoFile: "doubleme.jpg",
  },
  {
    slug: "h2o-hospitality",
    nameKo: "H2O호스피탈리티",
    nameEn: "H2O Hospitality",
    category: "Proptech",
    descriptionKo: `H2O호스피탈리티는 호텔, 리조트 등의 숙박 및 레저 산업의 디지털 전환을 선도하는 아시아 1위의 테크 기반 호스피탈리티 운영 기업이다. 국내에서 홈크리닝 서비스 '와홈'을 운영하던 이웅희 대표가 글로벌 시장 진출을…`,
    logoFile: "h2o-hospitality.jpg",
  },
  {
    slug: "impactus",
    nameKo: "임팩터스",
    nameEn: "IMPACTUS",
    category: "Edu-Tech",
    descriptionKo: `AI로 학생 개인 맞춤형 교육을 혁신하는 에듀테크 스타트업 '임팩터스'입니다. 임팩터스는 학생 개인 맞춤형 수업 개설–운영–피드백–평가를 지원하는 올인원 플랫폼 ‘임팩트 스페이스’를 운영합니다. 교사용 AI 에이전트…`,
    logoFile: "impactus.png",
  },
  {
    slug: "pierrot-company-inc",
    nameKo: "(주)피에로컴퍼니",
    nameEn: "Pierrot Company Inc.",
    category: "AI",
    descriptionKo: `피에로컴퍼니는 기업과 개인이 사용한 IT기기를 다시 자산으로 전환하여 글로벌 시장에 재배치하는 순환경제 기업입니다. 국내에서 IT기기 구독 서비스 phoneGO와 기업 유휴자산 회수 서비스 reGO를 운영하며, 회수…`,
    logoFile: "pierrot-company-inc.png",
  },
  {
    slug: "kangsters-corp",
    nameKo: "캥스터즈 주식회사",
    nameEn: "Kangsters Corp.",
    category: "Digital Health",
    descriptionKo: `캥스터즈는 장애로 인한 불편함을 깊이 공감하며, 이동 약자를 위한 포용적이고 혁신적인 기술을 만드는 소셜벤처입니다.주력 제품인 '휠리엑스'는 휠체어 사용자가 자신의 휠체어를 탄 채로 유산소 및 근력 운동을 할 수 있…`,
    logoFile: "kangsters-corp.png",
  },
  {
    slug: "zest-inc",
    nameKo: "제스트 주식회사",
    nameEn: "ZEST Inc.",
    category: "AI",
    descriptionKo: `제스트는 “탄소중립 최적화를 위한 AI-디지털 트윈 융합형 프리콘 Agent”를 개발하는 기후테크 스타트업입니다.초기에는 녹색 건설자재 공급망 관리 서비스 ‘그린북(Greenbook)’을 통해 약 13만 건 이상의 …`,
    logoFile: "zest-inc.png",
  },
  {
    slug: "genoplan",
    nameKo: "제노플랜",
    nameEn: "Genoplan",
    category: "Healthcare",
    descriptionKo: `제노플랜은 국내 유전자 분석 시장은 물론 일본 등 아시아인 유전 정보 분석 시장 분야에서 선두를 유지하고 있는 기업이다. 침 한 방울로 유전자를 분석해 다양한 건강 데이터를 확인할 수 있는 유전체진단키트를 선보이며 …`,
    logoFile: "genoplan.png",
  },
  {
    slug: "mbx",
    nameKo: "미미박스",
    nameEn: "MBX",
    category: "E-commerce",
    descriptionKo: `글로벌 멀티 뷰티 브랜드 및 퍼스널 케어 스타트업 미미박스(MBX)는 전세계 4천 여개 뷰티 브랜드가 입점한 이커머스 플랫폼을 운영하고 있다. 메이크업 전문 자체 개발 브랜드인 '아임미미(I'M MEME)'를 선보여…`,
    logoFile: "mbx.png",
  },
  {
    slug: "havehad",
    nameKo: "해브해드",
    nameEn: "havehad",
    category: "Fashion",
    descriptionKo: `해브해드는 도시의 일상을 다채롭게 즐기는 사람들을 위한 라이프스타일 브랜드를 전개하며, 일상에 새로운 영감을 더하는 감도 높은 기업입니다.`,
    logoFile: "havehad.png",
  },
  {
    slug: "obzen",
    nameKo: "오브젠",
    nameEn: "obzen",
    category: "AI",
    descriptionKo: `오브젠은 AI와 데이터 사이언스 기술을 기반으로 기업용 소프트웨어를 개발하는 AI 솔루션 기업입니다. 핵심 제품인 AI CRM 솔루션을 중심으로 ERP, SCM 등 주요 엔터프라이즈 시스템과 연계해 고객 데이터를 수…`,
    logoFile: "obzen.png",
  },
  {
    slug: "kokozi",
    nameKo: "코코지",
    nameEn: "kokozi",
    category: "Entertainment",
    descriptionKo: `코코지는 키즈 오디오 테크 스타트업으로, '코코지 하우스'와 캐릭터 오디오 콘텐츠인 '아띠(Arti)'를 통해 영유아에게 온오프라인 양방향으로 건강한 청각 자극을 제공하는 플랫폼을 운영합니다.`,
    logoFile: "kokozi.png",
  },
  {
    slug: "allganize",
    nameKo: "올거나이즈",
    nameEn: "Allganize",
    category: "Others",
    descriptionKo: `올거나이즈는 기업의 실제 업무 데이터를 기반으로 AI를 바로 실행 가능한 형태로 자동화하는 엔터프라이즈 AI 솔루션 'Alli'를 제공하는 기업입니다.`,
    logoFile: "allganize.png",
  },
  {
    slug: "gapt",
    nameKo: "갭텍",
    nameEn: "GAPT",
    category: "AI",
    descriptionKo: `갭텍은 반도체 특수가스 및 대기오염물질 저감 토탈 솔루션 기술과 장비를 보유하고 있으며, 탄소중립 CCUS 온실가스 저감 기술을 확장해 기관 및 대규모 사업장에 실증 적용하고 가스처리 고도화 기술까지 확보함으로써 저…`,
    logoFile: "gapt.png",
  },
  {
    slug: "shutagen",
    nameKo: "슈타겐",
    nameEn: "Shutagen",
    category: "Others",
    descriptionKo: `슈타겐은 자동차, 조선해양, 방산 및 철강 등 다양한 제조 산업 분야에서 Business Agilty 달성을 위한 산업 현장의 문제를 정의하고 솔루션을 제공하는 제조 디지털 전환 전문 엔지니어링 기업입니다.`,
    logoFile: "shutagen.png",
  },
  {
    slug: "gelko",
    nameKo: "젤코",
    nameEn: "GELKO",
    category: "AI",
    descriptionKo: `젤코는 자동화 연질캡슐 생산장비, 심리스 연질캡슐 생산장비, AI 비전검수기를 생산하는 기업입니다.`,
    logoFile: "gelko.png",
  },
  {
    slug: "slowave",
    nameKo: "슬로웨이브",
    nameEn: "Slowave",
    category: "AI",
    descriptionKo: `슬로웨이브는 신체건강에서 정신건강이 중요해지는 지금, 정신건강의 기초적인 Vital sign인 수면과 뇌파분석을 통해 정신건강 진단과 증진에 도움을 주는 초소형 뇌파 분석 기기, 슬로웨이브1.0를 개발하고 있습니다.…`,
    logoFile: "slowave.png",
  },
  {
    slug: "lehosah",
    nameKo: "르호사",
    nameEn: "LEHOSAH",
    category: "AI",
    descriptionKo: `르호사는 40년간 축적된 주얼리 제조 노하우와 40만 건 이상의 CAD 데이터를 기반으로, AI 주얼리 디자인 자동화 플랫폼 CHROMAKEY를 운영하는 테크 기반 주얼리 기업으로, 스케치 또는 텍스트 입력만으로 디…`,
    logoFile: "lehosah.png",
  },
  {
    slug: "beamstudio",
    nameKo: "빔스튜디오",
    nameEn: "Beamstudio",
    category: "AI",
    descriptionKo: `빔스튜디오는 자체 솔루션 BeamRealSolution을 통해 영화·방송(드라마) 등 하이엔드급 디지털 휴먼 콘텐츠를 제공하고 있으며, 배우·아티스트·스포츠 스타 등 유명인을 중심으로 한 디지털 휴먼 IP 에이전시 …`,
    logoFile: "beamstudio.png",
  },
  {
    slug: "logispot",
    nameKo: "로지스팟",
    nameEn: "logispot",
    category: "Logistics",
    descriptionKo: `디지털 플랫폼 기반의 고객 맞춤형 운송 및 W&D(Warehouse & Distribution) 전문 서비스를 제공하고 있는 로지스팟은 국내 산업 전반의 디지털 물류 혁신을 목표로 700개 이상의 기업…`,
    logoFile: "logispot.jpg",
  },
  {
    slug: "nthing",
    nameKo: "엔씽",
    nameEn: "N.Thing",
    category: "Agriculture",
    descriptionKo: `2014년 1월에 설립된 엔씽은 IT와 데이터를 접목해 농식품 분야 혁신과 푸드 밸류체인 혁신을 주도하는 글로벌 애그리-푸드 테크(Agri-food Tech) 스타트업이다. IT 기술과 데이터로 농식품 테크 시장 혁…`,
    logoFile: "nthing.png",
  },
  {
    slug: "sentbe",
    nameKo: "센트비",
    nameEn: "Sentbe",
    category: "Fintech",
    descriptionKo: `센트비는 더 싸고, 빠르고, 간편한 해외송금 서비스를 개발하고 있다. 해외송금 시장은 1년 거래액이 한국만 해도 40조 원에 달하는 큰 시장이다. 그런데 이 중 대부분을 차지하는 은행의 해외송금 서비스는 비싸고, 느…`,
    logoFile: "sentbe.png",
  },
  {
    slug: "qubit-security",
    nameKo: "큐비트시큐리티",
    nameEn: "Qubit Security",
    category: "Cybersecurity",
    descriptionKo: `큐비트시큐리티는 프루라 웹 방화벽(WAF)과 엔드포인트보안(EDR), 통합보안이벤트 관리시스템(SIEM)을 통해 고객사에 원스톱 토털 보안 서비스를 제공하는 국내 대표 기업이다.큐비트시큐리티의 솔루션은 시그니처 기반…`,
    logoFile: "qubit-security.jpg",
  },
  {
    slug: "paywork",
    nameKo: "페이워크",
    nameEn: "Paywork",
    category: "Fintech",
    descriptionKo: `페이워크는 프리랜서, 특수고용직을 위한 업무 정산 관리 서비스로써, 단기 계약으로 근무하는 '긱 워커'가 고객에게 쉽게 견적서를 생성하고 비용을 청구할 수 있도록, 여러 결제 기능을 제공하며, 사용자의 계좌연동을 통…`,
    logoFile: "paywork.jpg",
  },
  {
    slug: "liche",
    nameKo: "리체",
    nameEn: "LICHE",
    category: "Fintech",
    descriptionKo: `리체는 렌탈 비즈니스가 가장 발달한 한국의 렌탈 시스템을 혁신하여 다양한 고가 제품과 서비스를 장기 분할 납부할 수 있도록 하는 결제 시스템(LICHE BNPL)을 개발하였습니다. 이 시장을 검증하기 위해 리체 BN…`,
    logoFile: "liche.jpg",
  },
  {
    slug: "kupa",
    nameKo: "쿠파",
    nameEn: "KUPA",
    category: "Financials",
    descriptionKo: `쿠파(KUPA)는 글로벌 주식, ETF, 선물, 채권 및 옵션 데이터를 다이내믹 데이터 매핑(DDM)을 통해 심층 분석하는 인베스트테크 스타트업입니다. AI 기술과 업계 경험을 결합한 혁신적 플랫폼으로 실시간 시장 …`,
    logoFile: "kupa.jpg",
  },
  {
    slug: "draftype",
    nameKo: "드래프타입",
    nameEn: "Draftype",
    category: "AI",
    descriptionKo: `‘높은 섭외 비용’보다는, 소수의 빅모델이 독점할 수밖에 없는 구조 자체를 해결해야 하는 문제로 정의합니다. 이를 위해, 꼭 유명인이 아니더라도 효과적인 광고 모델 전략을 추구할 수 있는 옵션을 제공하는 기업`,
    logoFile: "draftype.jpg",
  },
  {
    slug: "databean",
    nameKo: "데이터빈",
    nameEn: "DataBean",
    category: "ESG",
    descriptionKo: `데이터빈은이머전 쿨링 기술과 엔지니어링 서비스가 검증된 국내 최초의 기업입니다. 데이터빈은 미래 세대를 위한 더 나은 데이터 센터를 만들기 위해 노력합니다.`,
    logoFile: "databean.jpg",
  },
  {
    slug: "stylemate",
    nameKo: "스타일메이트",
    nameEn: "Stylemate",
    category: "AI",
    descriptionKo: `패션 전문 마케팅 플랫폼, 패션 크리에이터 3천여명 및 국내 인기 브랜드 100여개 대상 서비스 중. 콘텐츠 성과 및 오디언스 분석 데이터와 자사 알고리즘 ‘룩태그'로 크리에이터 및 제작 콘텐츠 데이터 분석.`,
    logoFile: "stylemate.jpg",
  },
  {
    slug: "pulsead",
    nameKo: "펄스애드",
    nameEn: "PulseAd",
    category: "AD Tech",
    descriptionKo: `펄스애드는 AI 기반 통합 이커머스 광고 플랫폼으로, 리테일 셀러의 광고 운영 효율성을 극대화합니다. 아마존, 월마트 등 다양한 플랫폼의 광고를 한 곳에서 관리하고, AI 기반 실시간 입찰, 캠페인 자동 최적화, 맞…`,
    logoFile: "pulsead.jpg",
  },
  {
    slug: "itgreen",
    nameKo: "잇그린",
    nameEn: "Itgreen",
    category: "Sustainability",
    descriptionKo: `잇그린의 '리턴잇'은 배달음식에 사용되는 일회용기를 다회용기로 대체하는 친환경 서비스입니다. 위생적인 스테인리스 다회용기를 사용하고, 반납 시 남은 음식물 쓰레기까지 수거하는 리턴잇은 간편하게 식사하려는 직장인과 친…`,
    logoFile: "itgreen.jpg",
  },
  {
    slug: "whatap-labs",
    nameKo: "와탭랩스",
    nameEn: "WhaTap Labs",
    category: "Data Analytics",
    descriptionKo: `와탭랩스는 국내 최초 SaaS 기반 IT 통합 모니터링 서비스 기업으로, 국내에서 가장 많은 숫자인 1천여개 이상의 고객사를 보유하고 있다.와탭랩스의 모니터링 서비스 '와탭'은 기업 서버, 애플리케이션, 컨테이너 상…`,
    logoFile: "whatap-labs.jpg",
  },
  {
    slug: "uuuuu",
    nameKo: "유유유유유",
    nameEn: "UUUUU",
    category: "Beauty",
    descriptionKo: `UUUUU는 글로벌 콜라보레이션을 통해 감각적인 젤네일 디자인을 AI 프린트 시스템으로 양산하며 특허받은 신소재로 들뜸없이 밀착력되어 사용자의 만족도 높은 경험을 제공합니다.`,
    logoFile: "uuuuu.jpg",
  },
  {
    slug: "edgecross-1",
    nameKo: "엣지크로스",
    nameEn: "EDGECROSS",
    category: "Advertisement",
    descriptionKo: `다년간 축적된 S/W + H/W 기술로 개발시 필요한 것들을 각각 모듈화하여, 개발 기간을 최소 10배 이상 단축시킨 새로운 개념의 조립식 컨트롤러인,"모드링크[MODLINK]"를 개발 공급하고 있습니다.또한 소프트…`,
    logoFile: "edgecross-1.jpg",
  },
  {
    slug: "carmerce",
    nameKo: "카머스",
    nameEn: "CARMERCE",
    category: "E-commerce",
    descriptionKo: `카머스는 최초의 중고차 이커머스 플랫폼으로 복잡하고 불편했던 자동차 거래를 혁신적으로 해결합니다.`,
    logoFile: "carmerce.jpg",
  },
  {
    slug: "sparkpet-knollo",
    nameKo: "스파크펫 (놀로)",
    nameEn: "Sparkpet (KNOLLO)",
    category: "Pet",
    descriptionKo: `콘텐츠, 커머스, 공간의 핵심 서비스 영역을 중심으로, 반려동물과 보호자의 온오프라인 고객 경험을 연결하는 통합 플랫폼입니다.`,
    logoFile: "sparkpet-knollo.jpg",
  },
  {
    slug: "toothnote",
    nameKo: "지아이빌리언스 (투스노트)",
    nameEn: "toothnote",
    category: "Beauty",
    descriptionKo: `화학 성분을 제외하고 안전한 자연성분으로만 치약을 만듭니다. 투스노트와 함께 건강하고 즐거운 구강관리 시작하세요.`,
    logoFile: "toothnote.jpg",
  },
  {
    slug: "eatmapl",
    nameKo: "잇마플 (맛있저염)",
    nameEn: "Eatmapl",
    category: "Healthcare",
    descriptionKo: `잇마플은 환자별 정밀영양 식사관리 솔루션 ‘맛있저염’을 통해 환자의 건강상태, 질환 등 개인 데이터를 분석하여 맞춤형 식단 정기구독 서비스를 제공합니다. 개인 환자를 위한 식사요법 관리 솔루션뿐만 아니라, 병원과 보…`,
    logoFile: "eatmapl.jpg",
  },
  {
    slug: "vanilabrain-sellerking",
    nameKo: "바닐라브레인 (장사왕)",
    nameEn: "Vanilabrain (SELLERKING)",
    category: "E-commerce",
    descriptionKo: `바닐라브레인의 장사왕은 쇼핑몰별로 분산된 데이터를 장사왕 플랫폼에 연동하여 온라인 셀러가 한 눈에 자신의 매출 및 정산 데이터를 확인할 수 있게 합니다.`,
    logoFile: "vanilabrain-sellerking.jpg",
  },
  {
    slug: "astar-copykle",
    nameKo: "아스타 (카피클)",
    nameEn: "Astar (COPYKLE)",
    category: "AI",
    descriptionKo: `카피클은 최적화된 텍스트 콘텐츠를 실시간으로 제공하는 AI 카피라이팅 서비스 입니다. 크리에이터들은 카피클을 통해 소셜미디어, 제품 설명 및 블로그 아티클을 포함한 다양한 마케팅 카피라이트를 생성하여 시간과 리소스를…`,
    logoFile: "astar-copykle.jpg",
  },
  {
    slug: "mineis-charan",
    nameKo: "마인이스 (차란)",
    nameEn: "Mine.is (Charan)",
    category: "Commerce",
    descriptionKo: `유니클로 가격에 폴로를, 폴로 가격에 꼼데가르송을 제공하는 온라인 세컨핸드 백화점을 운영하고 있습니다`,
    logoFile: "mineis-charan.jpg",
  },
  {
    slug: "dosigotgan",
    nameKo: "도시곳간",
    nameEn: "Dosigotgan",
    category: "Commerce",
    descriptionKo: `도시곳간은 도시 소비자와 시골 생산자를 연결하는 공간으로, 300여 가지의 신선한 반찬과 요리를 제공하며, 다양한 PB 상품을 소개합니다. 또한 소규모 농부와 명・장인들과 협력하여, 그들의 이야기와 제품을 소개하고 …`,
    logoFile: "dosigotgan.jpg",
  },
  {
    slug: "medithings",
    nameKo: "메디띵스",
    nameEn: "MEDiThings",
    category: "Digital Health",
    descriptionKo: `메디띵스는 인공지능 및 바이오포토닉스 기술을 통해 배뇨장애 환자가 당면한 매일의 배뇨 문제를 해결하고 환자와 가족의 삶의 질을 개선할 수 있는 개인맞춤형 웨어러블 방광모니터링 솔루션을 제공합니다.`,
    logoFile: "medithings.jpg",
  },
  {
    slug: "baegen",
    nameKo: "배젠",
    nameEn: "Baegen",
    category: "Bio",
    descriptionKo: `배젠은 한의학의 '보도환'에서 만성폐쇄성폐질환(COPD)에 대한 치료제인 BG-519를 분리 합성해냈습니다. 근본적 치료제가 없어 고통받던 COPD 환자들에게 월등한 효과와 인체에도 안전한 치료제를 개발합니다.`,
    logoFile: "baegen.jpg",
  },
  {
    slug: "damhwa-company",
    nameKo: "담화컴퍼니 (술담화)",
    nameEn: "Damhwa Company",
    category: "Commerce",
    descriptionKo: `술담화는 취하기 위해 ‘부어라마셔라’가 아닌, 술자리에서의 담화를 위해 마시는 건강한 음주 문화를 만드는 소명을 가지고 탄생했습니다.이를 위해 만들고자 하는 미래 (비전)은 경험에서 가치로, 가치에서 일상으로. 즉 …`,
    logoFile: "damhwa-company.jpg",
  },
  {
    slug: "midbar",
    nameKo: "미드바르",
    nameEn: "Midbar",
    category: "Smart Farm",
    descriptionKo: `에어팜은 세계 최초 공기주입식 스마트팜으로, 0.5일 만에 설치하여 실내 어디서나 식량생산을 가능하게 합니다. 미스트 형태의 양분을 뿌리에 분사하는 에어로포닉스 농법과 작물이 증산한 수분을 다시 뿌리에 공급하는 기술…`,
    logoFile: "midbar.jpg",
  },
  {
    slug: "langcode-inc",
    nameKo: "주식회사 랭코드",
    nameEn: "Langcode Inc.",
    category: "AI",
    descriptionKo: `랭코드는 Mercedes-Benz 등 글로벌 엔터프라이즈를 포함한 30개 이상의 대기업 고객사로부터 인정받은 신뢰성과 확장성을 자랑하는 생성형 AI 플랫폼, 랭코드 CXP를 통해 기업의 AI 도입과 업무 혁신을 가속…`,
    logoFile: "langcode-inc.jpg",
  },
  {
    slug: "livit-tansolution",
    nameKo: "리빗 (탄솔루션)",
    nameEn: "LIVIT (TANSOLUTION)",
    category: "ESG",
    descriptionKo: `잦은 온실가스 관련 규제 변경으로 인해 대응비용이 예산을 초과하는 문제에 직면하고 있는 기업들을 대상으로 기업 내 전문인력이 없어도 변경되는 규제 및 공시기준이 자동 반영되는 기업용 온실가스 배출관리 솔루션을 제공하…`,
    logoFile: "livit-tansolution.jpg",
  },
  {
    slug: "accurie-biosciences",
    nameKo: "에큐리바이오",
    nameEn: "Accurie Biosciences",
    category: "Bio",
    descriptionKo: `에큐리바이오는 자연에서 파아지 분리 없이 인간유전체 분석을 통해 발굴된 가상의 파아지 DB를활용하여 원하는 세균을 표적하는 인공합성 파아지를 만드는 플랫폼 (enPhaG®)을 개발하고 있습니다. 이를 통해 종양미세환…`,
    logoFile: "accurie-biosciences.jpg",
  },
  {
    slug: "inogenix-inc-oncocheck",
    nameKo: "이노제닉스 (온코체크)",
    nameEn: "INOGENIX Inc. (ONCOCHECK)",
    category: "Bio",
    descriptionKo: `대장암은 대장용종으로부터 발생합니다. 이노제닉스의 혈액을 이용한 대장암 선별검사는 전 세계에서 유일하게 대장용종과 대장암을 90% 이상의 민감도로 진단합니다. 이노제닉스는 이 기술을 기반으로 2023년 바이오 기업 …`,
    logoFile: "inogenix-inc-oncocheck.jpg",
  },
  {
    slug: "amber-road-miner-report",
    nameKo: "앰버로드 (마이너리포트)",
    nameEn: "AMBER ROAD (MINER REPORT)",
    category: "AI",
    descriptionKo: `누구나 쉽게 AI를 활용해 제조 공정을 최적화 시킨다는 \`제조 AI 대중화\` 미션 아래 설립된 앰버로드는, POSCO 사내벤처로 지난 8년간 수많은 현장 AI 프로젝트를 수행한 현장 전문가들이 모여 만들어진 팀 입니…`,
    logoFile: "amber-road-miner-report.jpg",
  },
  {
    slug: "lucentblock-sou",
    nameKo: "루센트블록 (소유)",
    nameEn: "LUCENTBLOCK (SOU)",
    category: "Proptech",
    descriptionKo: `부동산 수익증권 거래 플랫폼 “소유”는 고가의 상업용 부동산을 수익 증권화해서 주식처럼 소액으로 사고 팔 수 있는 부동산 토큰 증권 플랫폼입니다. 일반투자자 누구나 투자 규모에 관계없이 소액으로도 거래가 가능 부동산…`,
    logoFile: "lucentblock-sou.jpg",
  },
  {
    slug: "bonjac-selvatico",
    nameKo: "본작 (셀바티코)",
    nameEn: "BONJAC (Selvatico)",
    category: "Cosmetic",
    descriptionKo: `주식회사 본작은 자연이 사람에게 주는 힘에서 영감을 받아 ‘있는 그대로의 자연’이란 뜻을 담은 셀바티코를 런칭하여, 세계적인 조향회사와 다이렉트로 제조 및 개발한 니치향료의 제품들과 프랑스 전통 제조방식이 담긴 마르…`,
    logoFile: "bonjac-selvatico.jpg",
  },
  {
    slug: "motiv-intelligence-onnuri-dmc",
    nameKo: "모티브인텔리전스 (온누리DMC)",
    nameEn: "Motiv Intelligence (Onnuri DMC)",
    category: "Advertisement",
    descriptionKo: `모티브인텔리전스는 광고 기술을 통해 기업 마케팅을 자동화시키고, 광고 지면을 보유한 미디어들의 수익을 창출해주는 애드테크 전문 기업입니다. CTV 광고 시장은 전세계적으로 빠르게 성장하며 온라인 동영상 광고 노출의 …`,
    logoFile: "motiv-intelligence-onnuri-dmc.jpg",
  },
  {
    slug: "ninehire-hackit",
    nameKo: "나인하이어",
    nameEn: "Ninehire (Hackit)",
    category: "HR tech",
    descriptionKo: `나인하이어는 여러 채용 채널에서 진행되는 지원자 관리와 채용에 필요한 모든 기능을 제공하고, 공고 작성부터 최종 합격까지 채용의 전 과정을 한 곳에 모아 관리하여 좋은 인재를 놓치지 않도록 돕는 HR 솔루션 입니다.`,
    logoFile: "ninehire-hackit.jpg",
  },
  {
    slug: "eargada-nadio",
    nameKo: "이어가다",
    nameEn: "Eargada [Nadio]",
    category: "Entertainment",
    descriptionKo: `이어가다의 ‘나디오’는 숏폼 오디오 에세이를 제작하고 공유하는 플랫폼입니다. 기존의 출판물을 오디오로 옮긴 오디오 북과는 달리, 소통과 힐링 기반의 에세이를 숏폼 오디오로 제공합니다. 100여명의 오디오 작가가 위로…`,
    logoFile: "eargada-nadio.jpg",
  },
  {
    slug: "metarpas",
    nameKo: "메타파스",
    nameEn: "Metarpas",
    category: "Data Analytics",
    descriptionKo: `메타파스의 'SOLVIT(솔빛)' 서비스는 태양광발전소 시설의 상태 및 결함에 대해 빠르고 정확한 인사이트를 제공하며, 드론기반의 열화상 촬영, 딥러닝기반 분석과 측위를 통해 기존의 검사 방법보다 훨씬 빠르고 정확하…`,
    logoFile: "metarpas.jpg",
  },
  {
    slug: "better-monday-korea",
    nameKo: "베러먼데이코리아",
    nameEn: "Better Monday Korea",
    category: "community",
    descriptionKo: `베러먼데이는 “ 일상이 즐거워지면 월요일이 기대된다 ” 라는 슬로건 아래, 일상에서 누구나 쉽게 접할수 있는 공간, 서비스, 제품을 재해석하여 직장인들에게 새롭게 라이프 스타일을 제공하는 온&오프라인 비즈니스…`,
    logoFile: "better-monday-korea.jpg",
  },
  {
    slug: "elroilab",
    nameKo: "엘로이랩",
    nameEn: "elroilab",
    category: "AI",
    descriptionKo: `엘로이랩의 'Spectral AI'는 인공지능과 초분광 카메라라는 특수 카메라를 이용하여 식품 공정 중에 발생하는 이물질을 검출하는 솔루션이다. 식품 제조 현장에서 기존 금속 검출기와 엑스레이 등은 금속과 경질 물질…`,
    logoFile: "elroilab.jpg",
  },
  {
    slug: "vi-korea-cays",
    nameKo: "브이아이코리아",
    nameEn: "VI Korea (Cays)",
    category: "Supply Chain & Logistics",
    descriptionKo: `브이아이코리아의 '케이즈' 서비스는 맞춤형 패키지 박스 제작 서비스로, 고객이 원하는 박스 형태, 사이즈, 수량 등의 정보를 입력하면 견적은 물론 3D 박스 프리뷰가 가능하고, 패키지 디자인에 필요한 박스 도면인 칼…`,
    logoFile: "vi-korea-cays.jpg",
  },
  {
    slug: "yol-cargo",
    nameKo: "욜카고",
    nameEn: "YOL CARGO",
    category: "Supply Chain & Logistics",
    descriptionKo: `와이오엘의 '욜카고' 서비스는 수출입기업에게 경제적이고 편리한 국제운송을 제공하는 디지털 포워딩 플랫폼으로, 24시간 자동견적을 비롯해, 화물 예약, 통관, 보험, 트래킹까지 국제운송의 전 과정을 온라인 상에서 확인…`,
    logoFile: "yol-cargo.jpg",
  },
  {
    slug: "tutoring",
    nameKo: "튜터링",
    nameEn: "Tutoring",
    category: "Education",
    descriptionKo: `튜터링은 언제 어디서나 실시간으로 글로벌 개인 튜터를 연결하여 실시간 스피킹 레슨을 제공하는 On-demand mLearning Platform이다. 레슨 화면에서 스트리밍 되는 관심사 기반의 다양한 토픽카드와 커뮤…`,
    logoFile: "tutoring.jpg",
  },
  {
    slug: "brots",
    nameKo: "브로츠",
    nameEn: "Brots",
    category: "Blockchain",
    descriptionKo: `브로츠는 새로운 아티스트의 음악을 30초 동안 들을 수 있는 앱으로, 트랙을 좋아하면 오른쪽으로, 그렇지 않으면 왼쪽으로 스와이프하여 평가합니다. 또한 사용자가 좋아한 아티스트의 근처 공연을 알려주는 기능과 같은 음…`,
    logoFile: "brots.jpg",
  },
  {
    slug: "thinggotingoland",
    nameKo: "틴고랜드",
    nameEn: "Thinggo(Tingoland)",
    category: "E-commerce",
    descriptionKo: `틴고랜드의 띵고는 국내, 외 판매 중인 100만 개 이상의 캐릭터 상품을 한자리에 모으고, 사용자 개개인의 관심사를 분석하여 판매되는지도 몰랐던 취향저격 상품을 맞춤 큐레이션하는 플랫폼 서비스이다.`,
    logoFile: "thinggotingoland.jpg",
  },
  {
    slug: "onesoftdigm",
    nameKo: "원소프트다임",
    nameEn: "Onesoftdigm",
    category: "Healthcare",
    descriptionKo: `휴대용 생체정보 측정기로 개인 생체정보를 분석하고, APP를 통해 개인 건강정보 및 맞춤형 헬스케어 컨텐츠를 제공 합니다.`,
    logoFile: "onesoftdigm.jpg",
  },
  {
    slug: "specter",
    nameKo: "스펙터",
    nameEn: "Specter",
    category: "HR tech",
    descriptionKo: `스펙터는 이름과 전화번호만으로 지원자가 재직했던 회사의 대표자/임원진이 작성한 평판을 10초만에 열람할 수 있는 서비스이다.`,
    logoFile: "specter.jpg",
  },
  {
    slug: "softlanders",
    nameKo: "소프트랜더스",
    nameEn: "SoftLanders",
    category: "Software",
    descriptionKo: `소프트랜더스는 기업의 임직원 해외파견에 필요한 서비스를 제공하는 기업용 리로케이션 플랫폼이다. 미국, 중국, 베트남 등 30개 주요 해외파견 국가에 대해 해외이사, 비자, 보험 등 10가지 이상 상품을 비교하여 매칭…`,
    logoFile: "softlanders.jpg",
  },
  {
    slug: "moverse",
    nameKo: "무버스",
    nameEn: "Moverse",
    category: "Entertainment",
    descriptionKo: `무버스는 메타버스와 버추얼휴먼, 그 외의 디지털 시장을 위한 3D 모션을 제공하는 서비스로, 창작자 인증을 기반으로 했습니다. 카이스트 출신과 엔터 콘텐츠 기획 전문가의 조합으로, 다양한 게임사 및 메타버스 플랫폼과…`,
    logoFile: "moverse.jpg",
  },
  {
    slug: "logstack",
    nameKo: "로그스택",
    nameEn: "Logstack",
    category: "Data Analytics",
    descriptionKo: `로그스택은 내부통제의 비효율을 극복하고 실시간으로 회계부정을 탐지하는 솔루션을 제공하는 스타트업입니다. 현대 기업의 내부통제 시스템에서는 보안 기록이 복잡하게 쌓이고 이를 분석하는 데에 많은 시간이 소요되었지만, 로…`,
    logoFile: "logstack.jpg",
  },
  {
    slug: "xcrew",
    nameKo: "엑스크루",
    nameEn: "Xcrew",
    category: "Travel/Hospitality",
    descriptionKo: `엑스크루는 MZ세대의 건강한 여가 활동을 지원하는 액티비티 플랫폼입니다. 건강하고 특별한 여가활동을 위해 창립되어 퇴근 후의 소중한 시간을 즐겁게 만들어줍니다. 전문 크루의 도움을 통해 다양한 액티비티를 제공하며, …`,
    logoFile: "xcrew.jpg",
  },
  {
    slug: "villagebaby",
    nameKo: "빌리지베이비",
    nameEn: "Villagebaby",
    category: "E-Commerce",
    descriptionKo: `빌리지베이비는 임신·육아 정보 제공 및 큐레이션 커머스 플랫폼인 '베이비빌리'의 운영사다. 디지털 정보에 익숙하고, 데이터 기반 이해력을 지닌 밀레니얼 부모를 주 타겟으로 하여 시기별로 맞춤형 육아 정보 및 임신, …`,
    logoFile: "villagebaby.jpg",
  },
  {
    slug: "reharvest",
    nameKo: "리하베스트",
    nameEn: "Re:harvest",
    category: "Sustainability",
    descriptionKo: `리하베스트는 식품 제조 공정에서 발생하는 부산물을 업사이클하여 밀가루를 대체하는 가루를 제조하여 B2C 및 B2B 식품을 만드는 국내 최초 푸드업사이클 전문 회사이다.현재는 식혜, 맥주의 제조 공정에서 발생되는 보리…`,
    logoFile: "reharvest.jpg",
  },
  {
    slug: "kitchen-in-the-lab",
    nameKo: "키친인더랩",
    nameEn: "Kitchen in the Lab",
    category: "Food",
    descriptionKo: `키친인더랩은 식품계 SPA 브랜드가 가능하도록, 기획-제조-판매-광고를 자체적으로 해결하는 국내 유일한 스타트업이다.보수적이고, 변화가 느린 식품계의 트렌드를 선도하는 ‘간편식의 트렌드 게임 체인저’라는 밸류 포지셔…`,
    logoFile: "kitchen-in-the-lab.jpg",
  },
  {
    slug: "ondo",
    nameKo: "온도",
    nameEn: "Ondo",
    category: "Design",
    descriptionKo: `신소재 및 기술특허로 D2C로 판매하는 북미타겟 윤리적 패션 브랜드 입니다.`,
    logoFile: "ondo.jpg",
  },
  {
    slug: "personal-ai",
    nameKo: "퍼스널에이아이",
    nameEn: "Personal AI",
    category: "Data Analytics",
    descriptionKo: `퍼스널에이아이는 최초의 On-Device 개인데이터 플랫폼으로 개인정보 수집 없는 개인 데이터를 안전하게 이용할 수 있는 플랫폼이다.`,
    logoFile: "personal-ai.png",
  },
  {
    slug: "casting",
    nameKo: "캐스팅",
    nameEn: "Casting",
    category: "Marketing",
    descriptionKo: `캐스팅은 다양한 분야의 인플루언서들과 개인적으로 소통할 수 있는 플랫폼이다. 팬들은 기존에 불가했던 인플루언서와의 개인적 소통을 할 수 있으며, 인플루언서는 팬들의 소통 니즈를 충족시키며 수익을 창출한다.현재 50명…`,
    logoFile: "casting.jpg",
  },
  {
    slug: "softment",
    nameKo: "소프트먼트",
    nameEn: "Softment",
    category: "HR tech",
    descriptionKo: `소프트먼트는 F&B 가맹 창업 시장에 공정한 거래를 할 수 있도록 지원하는 플랫폼이다.현재 창업인은 서비스 5개월 만에 창업 문의 총 300명 누적 금액 약 230억 원이 등록되어있다. 예비창업자는 창업인에서…`,
    logoFile: "softment.png",
  },
  {
    slug: "cloa",
    nameKo: "클로아",
    nameEn: "Cloa",
    category: "Data Analytics",
    descriptionKo: `클로아는 방대한 데이터를 실시간으로 처리하는데 최적화된 데이터 파이프라인 솔루션 입니다.`,
    logoFile: "cloa.jpg",
  },
  {
    slug: "octatco",
    nameKo: "옥타코",
    nameEn: "Octatco",
    category: "Cybersecurity",
    descriptionKo: `EzFinger는 생체인식기반의 강력한 인증 솔루션이다.현재 해킹의 80%는 직간접적으로 패스워드 유출에서 온다. 이 같은 문제는 현재의 인증방법이 비밀번호로 이뤄지고 많은 사람들이 비밀번호를 재사용하는데서 발생된다…`,
    logoFile: "octatco.jpg",
  },
  {
    slug: "rawlabs",
    nameKo: "로랩스 (에어서플라이)",
    nameEn: "Rawlabs",
    category: "E-commerce",
    descriptionKo: `에어서플라이는 중소기업을 위한 구매관리솔루션(MRO)이다.기존 구매관리솔루션은 도입비용이 높고 사용법이 어려워 중소기업들은 도입할 수 없었다.에어서플라이는 MRO커머스를 SaaS형 클라우드서비스로 제공하여 구매방법과…`,
    logoFile: "rawlabs.jpg",
  },
  {
    slug: "peopet",
    nameKo: "페오펫",
    nameEn: "Peopet",
    category: "E-commerce",
    descriptionKo: `페오펫은 혁신적인 간편 송금 서비스처럼 반려인들이 본인들의 강아지를 쉽게 모바일로 등록할 수 있는 간편 등록 서비스를 제공한다. 모바일로 쉽게 신청 후, 3일내로 동물등록번호 발급을 받고 주문한 목걸이와 등록증을 배…`,
    logoFile: "peopet.jpg",
  },
  {
    slug: "crepass",
    nameKo: "크레파스솔루션",
    nameEn: "CrePass",
    category: "Fintech",
    descriptionKo: `크레파스솔루션(CrePASS Solution)은 개인의 신용을 평가하는 방법을 다각화하여 더 많은 크레딧 상품이 유통될 수 있게 하는 것을 목표로 하는 플랫폼이다.금융정보위주의신용등급이 신용정보가 부족하거나 비슷한 …`,
    logoFile: "crepass.jpg",
  },
  {
    slug: "edgecross",
    nameKo: "엣지크로스",
    nameEn: "Edgecross",
    category: "IoT",
    descriptionKo: `㈜빛컨 - 임베디드 컨트롤러 전문기업.㈜빛컨의 IOT-Modlink은 스마트팩토리를 빠르고 간편하게 구현하는 기술로, H/W를 모듈로 조립해서 구성하고, 사용자에게 서버, 웹, APP등을 무료로 제공하는 서비스이다.…`,
    logoFile: "edgecross.jpg",
  },
  {
    slug: "veluga",
    nameKo: "벨루가",
    nameEn: "Veluga",
    category: "Food",
    descriptionKo: `크래프트 맥주와 페어링 야식을 한 달에 2회씩 정기 배달하는 멤버십 서비스입니다. 매번 새로운 크래프트 맥주를 선정하고 그에 어울리는 야식 메뉴를 개발/페어링합니다. 또한 수요 예측이 가능한 크래프트 맥주 도매 유통…`,
    logoFile: "veluga.jpg",
  },
  {
    slug: "perfitt",
    nameKo: "펄핏",
    nameEn: "Perfitt",
    category: "Data Analytics",
    descriptionKo: `Perfitt은 모두에게 더 쉽고 편리한 신발 쇼핑을 할 수 있는 세상을 만듭니다. 고객마다 정확한 사이즈 추천을 통해서 온라인에서 신발을 구매할 때도 반품이나 교환을 걱정하지 않아도 됩니다. Perfitt은 Dee…`,
    logoFile: "perfitt.jpg",
  },
  {
    slug: "peaches",
    nameKo: "피치스",
    nameEn: "Peaches",
    category: "Entertainment",
    descriptionKo: `Peaches는 자동차 라이프스타일을 기반으로 하는 스트릿 패션 브랜드입니다. 한국에서는 아직 생소하지만, 해외 젊은이들의 문화가 스케이트보드에서 자전거로 타는 문화로, 이제는 자신의 자동차를 꾸며 타는 문화로 흘러…`,
    logoFile: "peaches.png",
  },
  {
    slug: "knowre",
    nameKo: "노리",
    nameEn: "KnowRe",
    category: "Education",
    descriptionKo: `Knowre는 학생 맞춤형 수학교육 솔루션을 제공합니다. Knowre의 비전은 디지털 수학교육의 표준 플랫폼이 되어 전 세계 학생들이 자기주도적으로 맞춤형 수학 학습을 할 수 있도록 돕는 것입니다.Knowre는 현재…`,
    logoFile: "knowre.jpg",
  },
  {
    slug: "weplanet",
    nameKo: "위플래닛",
    nameEn: "WePlanet",
    category: "Data Analytics",
    descriptionKo: `위플래닛은 일상의 순간들을 손쉽게 기록할 수 있는 모바일 '라이프로그(life-log)' 서비스를 만들고 있다. 아이콘 기반의 체크인 방식을 통해 사용자의 일상을 빠르고 직관적으로 기록하고, 개인화된 인포그래픽스를 …`,
    logoFile: "weplanet.jpg",
  },
  {
    slug: "tapjoy-5rocks",
    nameKo: "탭조이 (파이브락스)",
    nameEn: "Tapjoy (5Rocks)",
    category: "Data Analytics",
    descriptionKo: `5Rocks는 ABLAR Company에서 회사명을 변경하고 모바일 게임사들이 손쉽게 데이터를 분석할 수 있는 툴인 5Rocks를 서비스 하고 있다. 이 외에도, 데이터 분석이 생소한 회사들에게 컨설팅 서비스를 지원…`,
    logoFile: "tapjoy-5rocks.jpg",
  },
  {
    slug: "zoyi",
    nameKo: "조이코퍼레이션",
    nameEn: "Zoyi",
    category: "Data Analytics",
    descriptionKo: `조이코퍼레이션은 자체 개발한 센서와 방문객들의 와이파이 및 블루투스 신호를 통해 이커머스에서만 활용 가능하던 고객 분석 서비스를 오프라인 리테일 사업자에게 제공했다. 대형 브랜드 체인점에서 중소형 매장까지 맞춤형 서…`,
    logoFile: "zoyi.jpg",
  },
  {
    slug: "landing-international",
    nameKo: "랜딩인터내셔널",
    nameEn: "Landing International",
    category: "E-commerce",
    descriptionKo: `랜딩인터내셔널은 고품질 브랜드 제조기업, 유통업체, 도소매업체와의 탄탄한 글로벌 네트워크를 바탕으로 각국의 우수 제품 제조사와 인터내셔널 파트너를 연결시켜 글로벌 브랜드로 거듭날 수 있도록 돕는 플랫폼이다. 인터내셔…`,
    logoFile: "landing-international.jpg",
  },
  {
    slug: "chartmetric",
    nameKo: "차트메트릭",
    nameEn: "Chartmetric",
    category: "Data Analytics",
    descriptionKo: `차트메트릭은 아티스트와 음악 산업 전문가들을 위한 올인원 플랫폼으로, 포괄적인 스트리밍, 소셜 및 관객 데이터를 제공하여 모든 사람이 음악에서 성공적인 경력을 만들 수 있도록 지원한다.차트메트릭은 전 세계 200만 …`,
    logoFile: "chartmetric.jpg",
  },
  {
    slug: "treeplanet",
    nameKo: "트리플래닛",
    nameEn: "TreePlanet",
    category: "Agriculture",
    descriptionKo: `트리플래닛은 다양한 방법으로 나무를 심을 수 있는 숲 조성 상품을 개발해 시민, 기업, 정부 기관에 제공하는 소셜 벤처로, 2050년까지 전 세계에 1억 그루의 나무를 심는 것을 목표로 한다. 2010년 김형수, 정…`,
    logoFile: "treeplanet.jpg",
  },
  {
    slug: "piquant",
    nameKo: "파이퀀트",
    nameEn: "Piquant",
    category: "Healthcare",
    descriptionKo: `파이퀀트는 분광학기반 성분 분석 솔루션 전문기업이다. 미세먼지 문제를 비롯해서 공기, 수질, 피부상태 등 다양한 방면에서 IoT, AI, Big Data를 사용하여 정밀하고 즉각적인 분석과 모니터링을 제공하는 시스템…`,
    logoFile: "piquant.jpg",
  },
  {
    slug: "lockin-company",
    nameKo: "락인컴퍼니",
    nameEn: "Lockin Company",
    category: "Cybersecurity",
    descriptionKo: `락인컴퍼니의 모바일 앱 보안 솔루션 LIAPP은 개발 완료된 앱을 업로드하기만 하면 추가적인 코딩 없이 보안 적용이 가능한 노코드 SaaS형 보안 서비스다. 이용자가 원하는 기간에 따라 제품을 구매하여 이용할 수 있…`,
    logoFile: "lockin-company.jpg",
  },
  {
    slug: "stayes",
    nameKo: "스테이즈",
    nameEn: "Stayes",
    category: "Proptech",
    descriptionKo: `스테이즈는 한국에 거주하고자 하는 외국인을 위한 부동산 O2O 서비스이다. 온라인 상담, 계약부터 CS까지 한국어, 중국어, 영어로 고객을 지원함으로써 세입자와 집주인 간의 언어 장벽을 제거하는 데 있어 중요한 역할…`,
    logoFile: "stayes.jpg",
  },
  {
    slug: "pentapress",
    nameKo: "펜타프레스",
    nameEn: "PentaPress",
    category: "Advertising & Media",
    descriptionKo: `펜타프레스는 국내 최초의 글로벌 사진전문 통신사이다. 2009년 설립된 펜타프레스는 국내와 전세계 25개국 40여 명의 사진가들이 정치, 경제, 사회, 스포츠, 연예, 문화 등 각 분야의 사진을 생산해내고 있으며 이…`,
    logoFile: "pentapress.jpg",
  },
  {
    slug: "ekne",
    nameKo: "에크네",
    nameEn: "EKNE",
    category: "Platform",
    descriptionKo: `㈜에크네는 '투고하다' 서비스로 창작자와 제작자를 연결하며 5.2만명의 사용자와 1.5만 MAU를 기록했습니다. 스파크랩의 21기 육성 프로그램에 선정되어 1억원의 시드투자를 받았고, 18주간의 육성을 통해 후속 투…`,
    logoFile: "ekne.jpg",
  },
  {
    slug: "topolog",
    nameKo: "토폴로그",
    nameEn: "Topolog",
    category: "Platform",
    descriptionKo: `2022년 창립된 '토폴로그'는 한국 기반의 세일즈 테크 플랫폼으로 B2B 파트너 매칭을 혁신적으로 지원합니다. 기업들의 고민인 영업 우선순위 결정, 결정권자 접근, 고객의 고충 파악에 도움을 줍니다. 기업 데이터를…`,
    logoFile: "topolog.jpg",
  },
  {
    slug: "hiritsoft",
    nameKo: "히릿소프트",
    nameEn: "Hiritsoft",
    category: "E-commerce",
    descriptionKo: `2021년 창립된 히릿소프트는 '메이더', iOS와 Android 앱을 무료로 손쉽게 제작하는 노코드 플랫폼으로 시장을 선도하고 있습니다. 이 클라우드 기반의 혁신은 소스코딩 없이 단 3분 만에 앱을 동시에 제작하며…`,
    logoFile: "hiritsoft.jpg",
  },
  {
    slug: "mangoplate",
    nameKo: "망고플레이트",
    nameEn: "MangoPlate",
    category: "Food",
    descriptionKo: `망고플레이트는 국내 맛집 20만여곳, 사용자 리뷰 70만건을 보유한 맛집 추천 플랫폼이다. 전문 에디터의 큐레이션과 빅데이터를 결합한 맛집 정보를 제공해 월간 200만 명의 사용자(MAU)가 방문한다.2013년 설립…`,
    logoFile: "mangoplate.jpg",
  },
  {
    slug: "splab",
    nameKo: "스플랩",
    nameEn: "Splab",
    category: "B2B Software & Services",
    descriptionKo: `2022년 설립된 스플랩은 B2B 스케줄링 자동화 솔루션을 제공하는 선두 기업이다. 최근 '스페이스'를 통해 행사 참가자 간 빠르고 효율적인 네트워킹 기회를 제공하며, 다양한 기관 및 기업과의 파트너십을 성공적으로 …`,
    logoFile: "splab.jpg",
  },
  {
    slug: "look-insight-yakollyeo",
    nameKo: "룩인사이트 (약올려)",
    nameEn: "Look Insight (YAKOLLYEO)",
    category: "E-commerce",
    descriptionKo: `㈜룩인사이트는 2018년 설립하여 '약올려'라는 B2B 전자상거래 플랫폼을 통해 의약품 유통 문제점을 해결하고자 한다.이 플랫폼은 불용재고약 문제를 중심으로 개발되었으며, 다양한 서비스를 제공하여 약업계의 숙원 과제…`,
    logoFile: "look-insight-yakollyeo.jpg",
  },
  {
    slug: "kzone",
    nameKo: "케이존",
    nameEn: "KZONE",
    category: "Supply Chain & Logistics",
    descriptionKo: `케이존은 국내 역물류 스타트업으로, 자체 개발한 ‘리맥스’ 솔루션을 통해 반품 및 악성 재고 관리에 특화되었다. 이 솔루션은 미국 아마존 SPN의 공식 서비스 사업자로 지정되며, 국내 스타트업 중 처음으로 SW 영역…`,
    logoFile: "kzone.jpg",
  },
  {
    slug: "fluentt",
    nameKo: "플루언트",
    nameEn: "FluentT",
    category: "Others",
    descriptionKo: `2021년 설립된 AI 모션캡쳐 전문기업 플루언트는 특별한 장치 없이 3D 아바타의 움직임을 실시간으로 구현하며, PC와 모바일에서의 표정 표현 문제도 해결해 준다. 최근에는 중기부의 팁스 프로그램에 선정되어 최대 …`,
    logoFile: "fluentt.jpg",
  },
  {
    slug: "vetflux",
    nameKo: "벳플럭스",
    nameEn: "Vetflux",
    category: "B2B Software & Services",
    descriptionKo: `AI 기반 '늘펫플러스'를 운영하는 벳플럭스가 팁스(TIPS)에 선정되어 최대 5억원의 연구개발 지원을 받게 되었다. 이 솔루션은 동물병원 업무 자동화에 초점을 맞춰, 진료 예약부터 고객 상담까지 전반적으로 관리한다…`,
    logoFile: "vetflux.jpg",
  },
  {
    slug: "ggq",
    nameKo: "지지큐",
    nameEn: "GGQ",
    category: "Gaming/eSports",
    descriptionKo: `지지큐컴퍼니는 2019년 설립된 한국의 e스포츠 기업입니다. 라이엇게임즈의 리그 오브 레전드 리플레이로 게임 코칭 AI를 훈련시켰습니다. AI는 플레이어의 행동 분석해 승률 변화를 체크합니다. B2B 모델은 e스포츠…`,
    logoFile: "ggq.jpg",
  },
  {
    slug: "billyo",
    nameKo: "빌리오",
    nameEn: "Billyo",
    category: "Entertainment",
    descriptionKo: `빌리오(Billyo)는 2020년 설립된 스타트업으로 크리에이터를 위한 촬영스튜디오, 연습실 등 다양한 공간을 예약할 수 있는 앱 서비스를 제공합니다. 전국 각지의 촬영 장소와 연습 공간을 한눈에 볼 수 있게 해, …`,
    logoFile: "billyo.jpg",
  },
  {
    slug: "amondy",
    nameKo: "아몬디",
    nameEn: "amondy",
    category: "Healthcare",
    descriptionKo: `아몬디케어와 함께 상담 일정부터 정산까지 한번에 관리하세요. 실시간 연동, 알림 발송, 일정 변경; 모든 것이 자동입니다. 더 이상 복잡한 행정 업무에 시간낭비하지 마세요. 상담의 전 과정을 아몬디케어와 함께 편리하…`,
    logoFile: "amondy.jpg",
  },
  {
    slug: "growth-fit",
    nameKo: "그로스핏",
    nameEn: "Growth Fit",
    category: "Data Analytics",
    descriptionKo: `그로스핏은 다양한 전문가들의 협업을 지원하는 동시에 애널리틱스 연계로 프로젝트 협업과정에서 발생하는 데이터와 분석 인사이트를 실시간으로 제공합니다. 프로젝트 관련 정보가 한눈에 보이도록 설계되었으며, 빠른 의사결정과…`,
    logoFile: "growth-fit.jpg",
  },
  {
    slug: "iclave",
    nameKo: "아이클레이브",
    nameEn: "iClave",
    category: "Fashion",
    descriptionKo: `아이클레이브(iClave)는 2015년에 창립된 한국 기반의 패션 분야 SaaS 스타트업입니다. 주력 서비스인 '로보MD'는 AI와 머신러닝을 통해 이커머스의 배너 등록 및 운영 업무를 신속하고 효율적으로 자동화합니…`,
    logoFile: "iclave.jpg",
  },
  {
    slug: "mask-moments",
    nameKo: "마스크모먼트",
    nameEn: "Mask Moments",
    category: "E-commerce",
    descriptionKo: `마스크모먼트는 소피아 홍 CEO의 리더십 아래 미국에서 빠르게 성장하고 있는 피부 관리 전자 상거래 스타트업입니다. 2021년과 2022년의 다양한 하이라이트를 통해 한국의 미용 및 피부 관리 방식의 깊은 이해와 전…`,
    logoFile: "mask-moments.jpg",
  },
  {
    slug: "moonriver",
    nameKo: "문리버",
    nameEn: "Moonriver",
    category: "Data Analytics",
    descriptionKo: `문리버의 아이템스카우트는 이커머스 셀러들이 쇼핑몰 운영에 필요한 데이터 솔루션을 제공하는 플랫폼이다.사용자들은 관심 상품의 검색량, 광고 단가, 경쟁 강도, 자신이 판매하는 상품의 노출 순위 등의 다양한 데이터를 손…`,
    logoFile: "moonriver.jpg",
  },
  {
    slug: "seoul-bund",
    nameKo: "서울번드",
    nameEn: "Seoul Bund",
    category: "E-commerce",
    descriptionKo: `서울번드는 동아시아 스타일의 리빙제품을 만날 수 있는 플랫폼이다.동아시아는 예로부터 고품질의 공예품을 만들어 왔다. 또한 세대를 거쳐 내려온 장인의 기술들은 발전을 거듭해왔다. 북유럽 리빙스타일이 전세계 라이프스타일…`,
    logoFile: "seoul-bund.jpg",
  },
  {
    slug: "shark-market",
    nameKo: "샤크마켓",
    nameEn: "Shark Market",
    category: "E-commerce",
    descriptionKo: `샤크마켓은 베트남 시장을 겨냥한 신선식품 배송 서비스이다.현재 베트남 시장은 빠르게 성장하고 있지만, 식품 딜리버리 플랫폼이 미흡하며 대부분 SNS 기반 또는 식당 호출 딜리버리에 그쳐있어 식품 안전에 대해 믿고 주…`,
    logoFile: "shark-market.jpg",
  },
  {
    slug: "gmg",
    nameKo: "지엠지",
    nameEn: "GMG",
    category: "Proptech",
    descriptionKo: `지엠지(GMG)는 비시민권자 또는 국적자가 해외의 주거용 부동산 자산을 구매할 수 있도록 돕는다. 매년 500억 달러 어치의 주거용 부동산이 외국 국민들에 의해 전세계적으로 매입되고 있지만, 물리적 거리상의 문제나 …`,
    logoFile: "gmg.jpg",
  },
  {
    slug: "lablaco",
    nameKo: "라블라코",
    nameEn: "Lablaco",
    category: "Blockchain",
    descriptionKo: `라블라코(Lablaco)는 새로운 패션 커머스 플랫폼으로, 패션 브랜드간의 온라인, 오프라인, 물류를 결합하여 소비자와 브랜드, 소매업체 간의 관계를 재정의하는 원스톱 옴니채널 솔루션을 제공한다. 또한 라블라코는 패…`,
    logoFile: "lablaco.jpg",
  },
  {
    slug: "oinng-pickit",
    nameKo: "오닝 (픽잇)",
    nameEn: "OINNG (PICKIT)",
    category: "E-Commerce",
    descriptionKo: `신발, 피규어, 앨범 등 개인의 주관적 관심사에 따라 무언가를 수집하는 행위는 오랫 동안 존재해 왔다.픽잇은 디지털 콜렉터블이라는 새로운 방식으로 자신이 좋아하는 것들을 수집하고 즐길 수 있는 특별한 공간을 제공함으…`,
    logoFile: "oinng-pickit.jpg",
  },
  {
    slug: "tkit",
    nameKo: "티킷",
    nameEn: "Tkit",
    category: "Entertainment",
    descriptionKo: `티킷(TKIT)은 누구나 이벤트를 홍보하고 티켓을 만들어 판매할 수 있는 플랫폼이다.대형 티켓 사이트에서 티켓을 오픈하는 것에 대한 장벽을 낮추고 공연 업계에서 성공한 컨텐츠를 이끌고 있는 UMF 대표의 노하우를 담…`,
    logoFile: "tkit.jpg",
  },
  {
    slug: "a-impact",
    nameKo: "에이임팩트",
    nameEn: "A-Impact",
    category: "Agriculture",
    descriptionKo: `에이임팩트(A-Impact)는 빅데이터 기반 인공지능(AI) 직거래 플랫폼 '어레인지(Arrange)'를 개발하고 운영하는 스타트업이다.문자, 카카오톡, 페이스북, 블로그, 인스타그램 등 SNS 채널을 통한 직거래중…`,
    logoFile: "a-impact.jpg",
  },
  {
    slug: "curiochips",
    nameKo: "큐리오칩스",
    nameEn: "CurioChips",
    category: "Healthcare",
    descriptionKo: `큐리오칩스(Curiochips)는 서울대학교 연구실창업 벤처기업으로 3차원 혈관구조를 체외에서 모사하고 이를 활용해 인체장기칩 플랫폼을 제공하는 스타트업이다.약물 개발을 위한 전임상 단계에서는 동물실험을 수행하게 되…`,
    logoFile: "curiochips.jpg",
  },
  {
    slug: "abuhakim",
    nameKo: "아부하킴",
    nameEn: "Abuhakim",
    category: "E-commerce",
    descriptionKo: `아부하킴(AbuHakim)은 한국 제조사들이 중동 소비자들에게 직접 제품을 판매하고 마케팅할 수 있도록 현지 언어, 문화, 결제, 배송에 최적화된 솔루션을 제공한다.중동은 제조업이 취약한 국가들이 대부분으로, 제조 …`,
    logoFile: "abuhakim.jpg",
  },
  {
    slug: "inpock",
    nameKo: "인포크",
    nameEn: "INPOCK",
    category: "E-commerce",
    descriptionKo: `인포크(Inpock)는 SNS에서 높은 파급력을 가진 인플루언서(influencer)들의 제품을 한 곳에 모은 오픈 마켓 플랫폼을 개발중이다.최근 인플루언서들의 활동 영역이 넓어지고 소비자들에 미치는 영향이 급격히 …`,
    logoFile: "inpock.jpg",
  },
  {
    slug: "vlogr",
    nameKo: "브이로거",
    nameEn: "Vlogr",
    category: "Entertainment",
    descriptionKo: `영상으로 소통하는 유튜브 시대이지만, 일반인들은 여전히 자신의 이야기를 편집된 영상으로 전하기 어렵다. Vlogr는 일반인들도 자막, 타이포그래피, 음악 등을 활용해 유명 유투버들이 사용하는 영상 편집 효과를 모바일…`,
    logoFile: "vlogr.jpg",
  },
  {
    slug: "fluid",
    nameKo: "플루이드",
    nameEn: "Fluid",
    category: "Advertising & Media",
    descriptionKo: `플루이드는 컨텐츠 소비자에게는 유연하고 직관적인 소비 경험을, 컨텐츠 생산자에게는 새로운 이익 창출 방법을 제공합니다. 플루이드는 소비자에게 보상을 주는 마케팅 플랫폼을 구성합니다. 또한 매출을 잠식시키는 광고 차단…`,
    logoFile: "fluid.jpg",
  },
  {
    slug: "zhenhub",
    nameKo: "젠허브",
    nameEn: "ZhenHub",
    category: "Supply Chain & Logistics",
    descriptionKo: `ZhenHub는 사용자가 단 한 번의 클릭으로 물류 작업을 실행할 수 있는 플랫폼을 제공함으로써, 글로벌 상거래(eCommerce)를 보다 쉽고 편하게 즐길 수 있도록 도와줍니다. 우리는 '공유 경제'를 통해, 풀필…`,
    logoFile: "zhenhub.jpg",
  },
  {
    slug: "genecast",
    nameKo: "진캐스트",
    nameEn: "Genecast",
    category: "Healthcare",
    descriptionKo: `진캐스트의 원천기술인 Internally Discriminated Priming System (IDPS)는 다른 기술과 비교할 수 없을 정도로 신속하고 정확하게 유전적 변이를 검출하는 혁신적인 시스템이다.모든 암의 …`,
    logoFile: "genecast.jpg",
  },
  {
    slug: "profound",
    nameKo: "프로파운드",
    nameEn: "Profound",
    category: "HRtech",
    descriptionKo: `프로파운드(Profound)는 전세계 다양한 비즈니스 전문가들을 연결해 그들의 지식과 인사이트를 제공하는 '비즈니스 스팟 컨설팅 마켓 네트워크'이다. 각 전문가들의 고유한 경험과 차별화된 지식을 제공하고 있으며, 현…`,
    logoFile: "profound.jpg",
  },
  {
    slug: "swingvy",
    nameKo: "스윙비",
    nameEn: "Swingvy",
    category: "HRtech",
    descriptionKo: `스윙비는 싱가포르에 본사를 둔 스타트업으로, 동남아 중소기업을 대상으로 클라우드 인사관리 소프트웨어를 제공한다. 직원의 입사부터 휴가 및 성과 관리, 급여 지급 등의 절차를 모두 자동화하여 중소기업들이 보다 효율적으…`,
    logoFile: "swingvy.jpg",
  },
  {
    slug: "kooding",
    nameKo: "쿠딩",
    nameEn: "Kooding",
    category: "Design",
    descriptionKo: `KOODING 은 전세계 2백만개의 로컬 패션 브랜드들과 19억명의 밀레니엄 세대를 연결하는 글로벌 패션 온라인 마켓플레이스이다. KOODING은 새로운 이커머스 비즈니스 모델을 구축하였으며 리얼타임 데이터 자동화 …`,
    logoFile: "kooding.jpg",
  },
  {
    slug: "jocoos",
    nameKo: "요쿠스",
    nameEn: "Jocoos",
    category: "Advertising & Media",
    descriptionKo: `Jocoos (요쿠스)는 동영상 전문 기술 회사로, 동영상 관련 분야 서비스 및 시스템 개발이 손쉽게 가능하도록 서버내 동영상 파일 변환 처리 (Transcoding) 기술로 다양한 영상파일이 모든 모바일 기기에서 …`,
    logoFile: "jocoos.jpg",
  },
  {
    slug: "blocko",
    nameKo: "블로코",
    nameEn: "Blocko",
    category: "AI",
    descriptionKo: `2014년에 설립된 블로코는 국내 유일의 블록체인 매니지드 서비스 회사로, 국내 기업용 블록체인 플랫폼 시장에서 독보적인 점유율을 확보하고 있다.블로코는 블록체인이라는 어려운 기술을 누구나 쉽게 사용할 수 있는 서비…`,
    logoFile: "blocko.png",
  },
  {
    slug: "water-strider",
    nameKo: "워터스트라이더",
    nameEn: "Water Strider",
    category: "Hardware",
    descriptionKo: `워터스트라이더는 3D 근접 공간 감지 원천 기술을 보유한 기업으로 필드 변화의 감지를 통한 비접촉 솔루션을 개발했다. 2021년에는 5G 케이블, 안테나 전문기업 센서뷰와 합작사를 설립했다. 지속되는 코로나 19로 …`,
    logoFile: "water-strider.jpg",
  },
  {
    slug: "slab-asia",
    nameKo: "에스랩아시아",
    nameEn: "S.Lab Asia",
    category: "Logistics",
    descriptionKo: `에스랩아시아는 대한민국을 대표하는 의약품 콜드체인 전문 기업입니다. 국내 COVID-19 백신 용기 시장 점유율 1위를 달성하며 전 국민 투여분의 약 70%에 해당하는 백신 운송에 기여했습니다. 또한, 의약품 콜드체…`,
    logoFile: "slab-asia.jpg",
  },
  {
    slug: "swatchon",
    nameKo: "스와치온",
    nameEn: "SwatchOn",
    category: "E-commerce",
    descriptionKo: `스와치온은 전세계 패션브랜드들을 위한 소재 소싱 플랫폼으로 시작하여, 패션 소재 생산자들과 패션브랜드들을 온라인 플랫폼으로 연결하고 효율적으로 소재 공급을 관리를 할 수 있는 웹서비스 SwatchOn을 개발했다. 스…`,
    logoFile: "swatchon.png",
  },
  {
    slug: "bringko",
    nameKo: "브링코",
    nameEn: "Bringko",
    category: "E-commerce",
    descriptionKo: `국내 최초로 한국의 모든 쇼핑몰에 있는 상품을 해외 교민들이 편리하게 구매할 수 있도록 도와주는 역직구 메타 서비스 입니다.`,
    logoFile: "bringko.jpg",
  },
  {
    slug: "xsync",
    nameKo: "엑씽크",
    nameEn: "xSync",
    category: "Entertainment",
    descriptionKo: `엑씽크(xSync)는 오프라인 행사에 참여하는 참가자들이 서로 네트워킹하고 이벤트에 참여할 수 있도록 인터랙티브한 기능들을 제공하는 이벤트 플랫폼이다. 이벤트 기획자들은 효율적으로 정보를 전달하고 네트워킹을 촉진할 …`,
    logoFile: "xsync.jpg",
  },
  {
    slug: "balaan",
    nameKo: "발란",
    nameEn: "Balaan",
    category: "E-commerce",
    descriptionKo: `발란은 유통구조 혁신과 IT 결합을 통해 거대한 150조 아시아 명품 시장의 문제를 해결하며 시장에서 가장 빠르게 성장하고 있는 명품 커머스 플랫폼이다. 선별된 국내 공급업체 및 해외 부티크와의 계약을 통해 국내에서…`,
    logoFile: "balaan.jpg",
  },
  {
    slug: "xbrain",
    nameKo: "엑스브레인",
    nameEn: "XBrain",
    category: "AI",
    descriptionKo: `엑스브레인은 머신러닝에 대한 전문적인 경험과 지식이 부족한 사람들도 쉽게 이를 활용할 수 있도록 돕는다. 전문 인력의 부재, 어려운 머신러닝 관련 소프트웨어 등 다양한 진입장벽으로 인해 머신러닝 기술이 여전히 삶의 …`,
    logoFile: "xbrain.jpg",
  },
  {
    slug: "fasket",
    nameKo: "패스켓",
    nameEn: "FASKET",
    category: "E-commerce",
    descriptionKo: `우리동네 배달마켓 패스켓은 온라인의 상품과 동시에 우리동네 맛집의 인기상품까지 전부 취합하여 구매자에게 1시간 내로 합배달 해주는 밀크런 퀵커머스 서비스를 제공합니다.`,
    logoFile: "fasket.jpg",
  },
  {
    slug: "collegenie-ai",
    nameKo: "컬리지니에이아이",
    nameEn: "Collegenie AI",
    category: "AI",
    descriptionKo: `EssayFit AI는 실제 아이비리그 전임 입학사정관들의 평가방식을 GPT 기반으로 구현하여, 미국대학 지원자들에게 신뢰할 수 있는 전문적 지원에세이 평가 및 학습전반을 책임지는 AI 튜터를 제공합니다.`,
    logoFile: "collegenie-ai.jpg",
  },
  {
    slug: "noda-labs",
    nameKo: "노다랩",
    nameEn: "Noda Labs",
    category: "Others",
    descriptionKo: `노다랩(Noda Labs)은 2020년 설립된 데이터 분석 전문 기업으로, 'KFoodBuyers'라는 빅데이터 기반의 B2B 무역거래플랫폼을 통해 해외 식품 공급사들에게 한국 식품 시장 분석을 제공합니다. 플랫폼은…`,
    logoFile: "noda-labs.jpg",
  },
  {
    slug: "bootalkuiti",
    nameKo: "부톡",
    nameEn: "Bootalk(Uiti)",
    category: "Proptech",
    descriptionKo: `'부톡(Bootalk)'은 2016년 설립된 프롭테크 스타트업으로, 고객 맞춤형 부동산 매물 추천 서비스를 제공한다. 서울대학교 GIS·LBS 연구실과 협력하여 AI를 활용한 부동산 공간추론 기술을 개발하였으며, 국…`,
    logoFile: "bootalkuiti.jpg",
  },
  {
    slug: "careerday-1",
    nameKo: "커리어데이",
    nameEn: "Careerday",
    category: "Others",
    descriptionKo: `커리어데이(CareerDay)는 IT부터 금융, 바이오, 반도체에 이르기까지 다양한 분야의 전문가와 기업을 섬세하게 매칭하는 HRtech 플랫폼입니다. 설립부터 지금까지 눈부신 성장을 거듭하며 HR 분야에서의 혁신을…`,
    logoFile: "careerday-1.jpg",
  },
  {
    slug: "standingtall",
    nameKo: "스탠딩톨",
    nameEn: "StandingTall",
    category: "Healthcare",
    descriptionKo: `2014년에 설립된 '스탠딩톨(StandingTall)'은 한국의 헬스케어 기업으로 척추보조기 '플렉스파인'의 제조 및 판매를 주력으로 하고 있습니다. 2023년에는 국내 넘어 수출을 통해 시장에서 경쟁력을 높이며,…`,
    logoFile: "standingtall.jpg",
  },
  {
    slug: "instant-tattoo-1",
    nameKo: "인스턴트타투",
    nameEn: "Instant Tattoo",
    category: "Fashion",
    descriptionKo: `인스턴트타투는 국내에서 처음 선보이는 건식 템포러리 타투 브랜드로, 단 10초 안에 리얼타투의 생동감을 재현합니다. 화려한 색상 팔레트와 섬세한 매트 텍스처를 통해 국내외 유명 아티스트들의 독창적인 디자인을 완벽하게…`,
    logoFile: "instant-tattoo-1.jpg",
  },
  {
    slug: "starteacher-tevaluewise",
    nameKo: "별별선생",
    nameEn: "StarTeacher (TEvalueWise)",
    category: "Education",
    descriptionKo: `2017년 9월 최초로 공무원 강사들에 대한 정보를 제공하며 서비스를 출시하였고, 2018년 9월 기준 공무원뿐 아니라, 교수, 영어, 외국어, 자격증과 유치원에 이르기까지 수십 만 명의 강사, 수 만 개 기관에 대…`,
    logoFile: "starteacher-tevaluewise.jpg",
  },
  {
    slug: "tella",
    nameKo: "텔라",
    nameEn: "Tella",
    category: "Education",
    descriptionKo: `텔라는 학습자가 채팅으로 원어민 전문 강사의 채팅과 실시간 교정을 받는 온디맨드 영어 회화 교육 서비스이다. 구글의 자연어 처리 기술로 학습자의 영어 채팅 데이터를 분석하여 고객의 영어 사용 패턴과 숙련도를 진단하고…`,
    logoFile: "tella.jpg",
  },
  {
    slug: "xelin",
    nameKo: "세린",
    nameEn: "Xelin",
    category: "Hardware",
    descriptionKo: `반도체는 사용 분야의 변화에 따라 더 작아지고, 얇아지며, 다층화되고 있으나 기존 반도체 공정 방식은 발열 및 파티클 제어, Depth Control 불가능이라는 한계점을 갖고 있다.세린의 Micro-Dicing 레…`,
    logoFile: "xelin.jpg",
  },
  {
    slug: "spiceware",
    nameKo: "스파이스웨어",
    nameEn: "Spiceware",
    category: "Cybersecurity",
    descriptionKo: `스파이스웨어(Spiceware)는 클라우드 컴퓨팅 사용 고객들의 시스템과 주요 데이터를 보호할 수 있는 보안 플랫폼 제공을 목표로 하는 스타트업이다. 클라우드 환경에서 적용하기 힘든 기존 DB 암호화 솔루션의 단점을…`,
    logoFile: "spiceware.jpg",
  },
  {
    slug: "whelp",
    nameKo: "웰프",
    nameEn: "Whelp",
    category: "AI",
    descriptionKo: `웰프(Whelp)는 세일즈 및 고객관리 직원들이 서로 다른 대화 채널을 사용하는 고객들과 한 곳에서 소통할 수 있게 도와주는 플랫폼이다.기업들은 고객과의 소통을 위해 한 번에 6개가 넘는 대화 채널을 사용하며, 이로…`,
    logoFile: "whelp.jpg",
  },
  {
    slug: "paywatch-global",
    nameKo: "페이워치",
    nameEn: "Paywatch Global",
    category: "Fintech",
    descriptionKo: `페이워치(Pay Watch)는 시급제 근로자의 채용과 계약, 출퇴근 승인관리, 실시간 급여 정산 및 지급이 이뤄지는 원스톱 HR 서비스 플랫폼이다.블록체인 기술을 통해 근로자별 HR 관련 정보를 효율적으로 기록 및 …`,
    logoFile: "paywatch-global.jpg",
  },
  {
    slug: "caredoc",
    nameKo: "케어닥",
    nameEn: "Caredoc",
    category: "Healthcare",
    descriptionKo: `케어닥(caredoc)은 국가기관 평가와 실사용자 후기를 통해 검증된 정보를 기반으로 노인 돌봄 서비스 및 요양 시설 중개하는 사용자 맞춤형 플랫폼이다. 한국이 본격적인 고령사회에 진입함에 따라 노인 인구증가와 함께…`,
    logoFile: "caredoc.png",
  },
  {
    slug: "bitbyte",
    nameKo: "비트바이트",
    nameEn: "Bitbyte",
    category: "Entertainment",
    descriptionKo: `'플레이키보드(PlayKeyboard)'는 좋아하는 캐릭터, 연예인, 또는 다양한 디자인으로 나만의 스마트폰 키보드를 꾸밀 수 있는 앱이다.특히 입력하는 키워드에 따라 캐릭터나 연예인이 반응하거나 움직이는 '라이브테…`,
    logoFile: "bitbyte.jpg",
  },
  {
    slug: "featuring",
    nameKo: "피처링",
    nameEn: "Featuring",
    category: "Data Analytics",
    descriptionKo: `피처링(Featuring)은 SNS 인플루언서의 ‘진짜' 영향력을 측정해주는 플랫폼을 제공한다.다양한 브랜드가 인플루언서를 통한 여러 유형의 마케팅 캠페인을 진행하지만, 인플루언서 계정의 Fake followers …`,
    logoFile: "featuring.jpg",
  },
  {
    slug: "smartjack",
    nameKo: "스마트잭",
    nameEn: "SmartJack",
    category: "Data Analytics",
    descriptionKo: `랩매니저는 연구실 관리 솔루션 입니다. 대부분 연구실이 장부를 수기 작성하는 등, 수십년 전 아날로그 방식 그대로 관리되고 있습니다. 이로 인한 시간/비용의 비효율과 안전사고 위험을 랩매니저가 해결합니다. 랩매니저는…`,
    logoFile: "smartjack.jpg",
  },
  {
    slug: "activity-exchange",
    nameKo: "액스(AX)",
    nameEn: "Activity Exchange",
    category: "Travel/Hospitality",
    descriptionKo: `AX (액스)는 전세계 현지 여행사를 위해 여행상품 퍼블리싱과 예약관리 솔루션을 개발하는 스타트업이다. 현지 여행사는 AX (액스) 솔루션을 통해 수 십개의 온라인 판매채널에 한 번에 여행상품을 퍼블리싱할 수 있으며…`,
    logoFile: "activity-exchange.jpg",
  },
  {
    slug: "global-bridge",
    nameKo: "글로벌브릿지",
    nameEn: "Global Bridge",
    category: "Cybersecurity",
    descriptionKo: `글로벌 브릿지(Global Bridge)는 대용량 데이터 전송이 가능하고 보안성이 보장된 바이너리 CDMA기술을 보유하고 있는 회사이다.보안 알고리즘과 무선 데이터 송수신 장치의 핵심 기술 및 특허를 보유하고 있으며…`,
    logoFile: "global-bridge.jpg",
  },
  {
    slug: "thirteenth-floor",
    nameKo: "서틴스플로어",
    nameEn: "Thirteenth Floor",
    category: "AR",
    descriptionKo: `서틴스플로어는 VR 업계의 넷플릭스가 되고자 한다.세계적 수준의 Cinematic, Interactive VR 콘텐츠를 모두 제작할 수 있는 제작 능력과 Immersive Audio, 그리고 제작 전 과정을 내부에서…`,
    logoFile: "thirteenth-floor.jpg",
  },
  {
    slug: "simple-kitchen-hat-company",
    nameKo: "심플키친",
    nameEn: "Simple Kitchen (HAT Company)",
    category: "Proptech",
    descriptionKo: `심플키친(Simple Kitchen)은 외식업 창업자들에게 주방 공간과 시설을 제공해주고 다양한 비용들을 공유하게 함으로써 비용은 낮추고 매출은 극대화 할 수 있도록 하는 공유주방 플랫폼이다.전문가들의 노하우를 바탕…`,
    logoFile: "simple-kitchen-hat-company.jpg",
  },
  {
    slug: "fleapop",
    nameKo: "플리팝",
    nameEn: "Fleapop",
    category: "E-commerce",
    descriptionKo: `플리팝은 리테일 테크 기업입니다. 현재 10~20대 여성들을 위한 Experience Commerce를 제공하고 있으며 2일 기준 3만 명 이상의 고객들이 방문하고 있습니다. 플리팝은 Experience Commer…`,
    logoFile: "fleapop.jpg",
  },
  {
    slug: "emolize-payvil",
    nameKo: "에몰라이즈",
    nameEn: "Emolize (payvil)",
    category: "Financial Services",
    descriptionKo: `에몰라이즈㈜는 국제 결제 서비스를 위해서 설립된 Fintech 업체입니다.Payvil이란 앱 서비스를 진행하고 있으며, 현재 국내에서는 12,000 매장에서 결제가 가능한 상태입니다. 결제 수단은 알리페이와 계약을 …`,
    logoFile: "emolize-payvil.jpg",
  },
  {
    slug: "kadho",
    nameKo: "캐드호",
    nameEn: "Kadho",
    category: "Edutech",
    descriptionKo: `캐드호(Kadho)는 두뇌 훈련 커리큘럼 전문 기업으로, 뇌 과학 분야의 최신 연구결과와 인공지능 및 머신러닝 분야의 지식을 결합해 전문 지식 습득을 가속한다. 이들은 개인의 성과를 향상할 수 있는 인터랙티브 소비자…`,
    logoFile: "kadho.jpg",
  },
  {
    slug: "the-clozet",
    nameKo: "더클로젯컴퍼니",
    nameEn: "The Clozet",
    category: "Design",
    descriptionKo: `더클로젯(The Clozet)은 패션 분야의 에어비앤비를 지향하는 패션 공유 서비스이다. 고객 개개인을 연결해 평소 활용도가 낮은 패션 아이템을 공유하여 수익을 내고, 합리적인 가격으로 편리하게 다른 사용자의 패션 …`,
    logoFile: "the-clozet.jpg",
  },
  {
    slug: "asian-boss",
    nameKo: "아시안보스",
    nameEn: "Asian Boss",
    category: "Advertising & Media",
    descriptionKo: `아시안보스(Asian Boss)는 아시아 전역의 최신 뉴스와 트랜드를 전세계에 전달하는 뉴미디어 기업이다. 모바일에 최적화된 리포트 형식과 독창적인 길거리 현장 인터뷰 포맷을 통해 아시아의 다양한 사회적 이슈들과 이…`,
    logoFile: "asian-boss.jpg",
  },
  {
    slug: "kloser",
    nameKo: "클로저",
    nameEn: "Kloser",
    category: "Marketing",
    descriptionKo: `클로저는 고객채널 관리 플랫폼을 클라우드로 제공하는 마케팅 테크 전문 기업이다. 가장 효과적이고 신뢰도 높은 홍보 채널은 고객의 이야기이며, 클로저는 채널로서의 고객을 관리하는 도구이다. 클로저는 기업의 웹사이트나 …`,
    logoFile: "kloser.jpg",
  },
  {
    slug: "queensbucket",
    nameKo: "쿠엔즈버킷",
    nameEn: "QueensBucket",
    category: "Food",
    descriptionKo: `쿠엔즈버킷은 우리가 예전부터 먹고 자란 참기름, 들기름을 기존과는 전혀 다른 제조방식으로 만드는 제조회사이다. 쿠엔즈버킷의 기름은 맛과 향은 기계적 착유 방식으로 제조한 기름보다 훨씬 옛날 고유의 맛에 가까우며, 원…`,
    logoFile: "queensbucket.jpg",
  },
  {
    slug: "paymonths",
    nameKo: "페이먼스",
    nameEn: "Paymonths",
    category: "Fintech",
    descriptionKo: `파이노버스랩이 개발한 페이먼스는 머신러닝 기반의 신용평가를 활용한 국내 최초의 후불결제 서비스(BNPL: Buy Now Pay Later)이다.`,
    logoFile: "paymonths.jpg",
  },
  {
    slug: "urbanbase",
    nameKo: "어반베이스",
    nameEn: "Urbanbase",
    category: "AR",
    descriptionKo: `어반베이스는 2014년 설립된 3D 공간데이터 전문 기업으로, 2D 도면을 3D로 자동 변환하는 모델링 기술과 가상현실(VR), 증강현실(AR) 등 메타버스 영역의 핵심 기술을 보유하고 있다.어반베이스의 사업 영역으…`,
    logoFile: "urbanbase.jpg",
  },
];